## Get all HuBMAP IDs in the HRApop Atlas

In [4]:
# install and import libraries
%pip install pandas requests

import pandas as pd
import requests 
import json

Requirement already satisfied: pandas in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: requests in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (2.32.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (2025.1.31)
Requirement already satisfied: six>=1.5 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
# global settings
hra_pop_version = 'v1.0'
branch = 'main'

In [6]:
# load HRApop reports
url = f'https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/{branch}/output-data/{hra_pop_version}/reports/universe-ad-hoc/sankey.csv'
sankey = pd.read_csv(url)
sankey

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_27464\2608939130.py:3: DtypeWarning: Columns (1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  sankey = pd.read_csv(url)

,portal,study_paper,doi,lead_author,is_azimuth_reference,donor_id,donor_sex,donor_age,donor_development_stage,donor_race,...,unique_dataset_id,link_to_h5ad_file,sc_transcriptomics_or_sc_proteomics,cell_type_annotation_tool,omap_id,number_of_cells_total,number_of_unique_cell_types,hubmap_dataset_publication_status,is_rui_registered,is_atlas_dataset
0,HCA,NaN,NaN,NaN,NaN,TSP27,Female,56.0,NaN,NaN,...,hhttps://api.cellxgene.cziscience.com/dp/v1/co...,https://cellxgene.cziscience.com/e/a357414d-20...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
1,KPMP,NaN,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,Donor1,Male,NaN,NaN,NaN,...,http://dx.doi.org/10.1681/ASN.2016091027#Donor...,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,NaN,NaN,NaN,NaN,True,False
2,KPMP,NaN,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,Donor2,Male,NaN,NaN,NaN,...,http://dx.doi.org/10.1681/ASN.2016091027#Donor...,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,NaN,NaN,NaN,NaN,True,False
3,KPMP,NaN,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,Donor3,Male,NaN,NaN,NaN,...,http://dx.doi.org/10.1681/ASN.2016091027#Donor...,http://dx.doi.org/10.1016/j.trsl.2017.07.006,NaN,NaN,NaN,NaN,NaN,NaN,True,False
4,HRA,NaN,NaN,NaN,NaN,Donor1,Female,38.0,NaN,NaN,...,http://purl.org/ccf/1.5/omap-1#Donor1_TissueBl...,https://hubmapconsortium.github.io/ccf-release...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22178,SPARC,NaN,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,Donor1,Female,49.0,NaN,NaN,...,https://sparc.science/datasets/390/version/1?d...,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22179,SPARC,NaN,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,Donor1,Female,49.0,NaN,NaN,...,https://sparc.science/datasets/390/version/1?d...,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22180,SPARC,NaN,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,Donor1,Female,49.0,NaN,NaN,...,https://sparc.science/datasets/390/version/1?d...,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22181,KPMP,NaN,https://www.nature.com/articles/s41467-023-389...,NaN,NaN,Donor1,Male,NaN,NaN,NaN,...,https://zenodo.org/records/7653239#Donor1_Tiss...,https://zenodo.org/records/7653239,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22182,KPMP,NaN,https://www.nature.com/articles/s41467-023-389...,NaN,NaN,Donor2,Female,NaN,NaN,NaN,...,https://zenodo.org/records/7653239#Donor2_Tiss...,https://zenodo.org/records/7653239,NaN,NaN,NaN,NaN,NaN,NaN,True,False

In [7]:
sankey[(sankey['dataset_id'].str.contains('hubmap')) & (sankey['is_atlas_dataset'] == True)]['dataset_id'].nunique()

444

In [8]:
sankey[(sankey['portal'].str.contains('HuBMAP')) & (
    sankey['is_atlas_dataset'] == True)]['dataset_id'].nunique()

469

In [9]:
# filter for HuBMAP dataset IDs
hubmap_ids = sankey[(sankey['portal'].str.contains('HuBMAP')) & (sankey['is_atlas_dataset'] == True)][[
    'portal', 'dataset_id', 'organ_name']]

hubmap_ids_filtered = hubmap_ids.drop_duplicates(subset=['dataset_id'], keep='first')
hubmap_ids_filtered

,portal,dataset_id,organ_name
16039,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine
16040,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine
16041,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine
16042,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine
16043,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine
...,...,...,...
20565,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney
20576,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney
20577,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney
20580,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,large intestine
20584,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,urinary bladder

In [10]:
# isolate UUID
hubmap_ids_filtered['uuid'] = hubmap_ids_filtered['dataset_id'].apply(
    lambda d: d.split('/')[len(d.split('/'))-1])
hubmap_ids_filtered

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_27464\645982474.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hubmap_ids_filtered['uuid'] = hubmap_ids_filtered['dataset_id'].apply(

,portal,dataset_id,organ_name,uuid
16039,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01002
16040,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01007
16041,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01014
16042,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01020
16043,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01025
...,...,...,...,...
20565,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney,fe0ded5fc0355c95239f9c040dd31e99
20576,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney,fee4cf0e7da557d3ef5c535b5417ed7a
20577,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney,feea9accbe57b7a052563895ac543d91
20580,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,large intestine,ff5d0d740fea8963e91f2e35c0a85596
20584,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,urinary bladder,ffade7fd19cebd25cd9a9fab2111cb09

In [11]:
# add HuBMAP IDs in addition to UUIDs
entity_api = f'https://entity.api.hubmapconsortium.org/datasets/'

def try_hubmap_id(url):
  """Tries to get a hubmap_id from an API response

  Args:
      url (str): URL for Entity API 
  """
  response = ''
  try:
    response = json.loads(requests.get(url).text)['hubmap_id']
    print(response)
    return response
  except:
    response = "no hubmap_id found"
    print(response)
    return response
    

hubmap_ids_filtered['hubmap'] = hubmap_ids_filtered['dataset_id'].apply(lambda d: try_hubmap_id(d))
hubmap_ids_filtered

no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
no hubmap_id found
HBM465.RKKK.264
HBM232.FHDF.343
HBM927.DZCV.762
HBM556.KSFB.592
HBM699.GZNP.474
HBM793.JDRF.289
HBM633.JXTC.477
HBM623.PSDG.665
HBM976.MRWH.263
HBM795.TFHS.265
HBM962.KQLZ.422
HBM732.FZVZ.656
HBM844.RXXR.293
HBM495.ZFDT.229
HBM768.FKCS.477
HBM688.RPFC.258
HBM693.SRHJ.546
HBM839.ZFRD.789
HBM735.FSBZ.626
HBM644.NKCL.897
HBM374.PCQG.742
HBM468.SSXX.967
HBM264.MJCH.639
HBM793.TLNJ.249
HBM757.KLKW.524
HBM746.VTDZ.959
HBM979.KNQM.454
HBM689.ZKRJ.585
HBM934.KLGL.584
HBM547.TFRR.794
HBM232.MGHW.694
HBM455.RZPH.997
HBM996.XSNK.694
HBM237.TJFZ.599
HBM945.FSHR.864
HBM936.MHTZ.834
HBM893.MCGS.487
HBM389.PKHL.936
HBM269.GDLH.894
HBM999.KMVN.849
HBM528.DMSV.294
HBM439.WJDV.974
HBM393.DZDZ.972
HBM675.RVGB.258
HBM546.RNHX.756
HBM265.PCGD.229
HBM975.WQQQ.853
HBM385.LQVK.975
HBM537.GVTL.683
HBM284.MNHF.223
HBM996.MDQH.988
HBM398.BLRW.228
HBM843.CLTD.457
HBM626.PHCW.834
HBM522.FTFK.487
HBM687.SJLD.889
HBM855.HPDG.442
HBM255.QMNS.733
HBM526.WCCD.472
HBM666.JCGS.862
HBM236.JPVT.769
HBM599.GNJN.777
HBM578.BDBP.672
HBM793.RPMP.954
HBM456.XDCK.572
HBM434.HHJG.856
HBM953.KMTG.758
HBM728.SRDD.525
HBM675.VBDH.688
HBM867.NVKS.443
HBM276.ZCGM.239
HBM927.FWCN.753
HBM947.NLPP.426
HBM958.GZCX.985
HBM395.WSDD.355
HBM429.LLRT.546
HBM265.HMJZ.658
HBM368.MPRF.249
HBM552.PBBF.363
HBM348.TWMS.895
HBM333.XMCV.992
HBM528.KNNX.327
HBM356.MDPN.792
HBM294.CHCQ.358
HBM296.KZXD.676
HBM846.KVCF.674
HBM364.XLVH.839
HBM776.GZVW.552
HBM444.DXLZ.643
HBM297.FDTX.382
HBM536.FHLK.529
HBM427.KFXP.323
HBM393.SNVZ.737
HBM887.DDJL.589
HBM995.NPWL.939
HBM456.CGDP.395
HBM957.TXXZ.387
HBM475.CVXD.875
HBM535.QNTP.246
HBM353.NZVQ.793
HBM476.ZLDJ.925
HBM342.CMHT.948
HBM743.RNWC.765
HBM299.VDWT.444
HBM626.VJMB.795
HBM969.PBMH.689
HBM425.GDJT.648
HBM929.VSJQ.633
HBM689.XCBK.436
HBM868.CXJM.449
HBM822.KRLC.323
HBM666.RBCG.529
HBM349.QCWZ.339
HBM467.RQDN.922
HBM877.JFMS.222
HBM593.JLCT.283
HBM223.RVJG.329
HBM787.WSCS.874
HBM657.JXDD.239
HBM438.JXJW.249
HBM673.GSSW.364
HBM455.HBZX.789
HBM727.DMKG.675
HBM344.SXNJ.874
HBM322.XJQZ.894
HBM664.LQSH.693
HBM292.MTQK.563
HBM582.CXXZ.438
HBM937.DWCD.722
HBM282.BKRZ.254
HBM438.BGFJ.559
HBM362.JVGH.934
HBM439.BQLR.867
HBM525.LRPL.332
HBM772.TKCN.287
HBM729.XTBN.693
HBM375.THCD.382
HBM389.MDVM.457
HBM244.QJFT.664
HBM262.LMHQ.472
HBM253.ZBGF.863
HBM928.THDD.545
HBM893.JVLB.845
HBM536.BTZP.293
HBM737.XZCH.767
HBM364.SJBR.333
HBM295.SWJJ.888
HBM248.SGCJ.257
HBM368.JCBG.263
HBM395.NQKF.566
HBM243.MTZV.726
HBM363.FVKP.935
HBM248.HPXX.584
HBM938.WTSR.492
HBM674.FLVW.576
HBM683.NRPR.962
HBM592.RPKF.946
HBM522.QXVG.468
HBM898.XQTL.438
HBM874.JPGB.398
HBM629.GSHG.922
HBM892.JLFV.844
HBM326.DMVL.323
HBM832.WTNH.257
HBM989.WFLC.569
HBM879.SGNW.944
HBM398.NCVN.256
HBM964.FPNH.767
HBM796.PCWD.863
HBM873.NSHG.559
HBM394.VSKR.883
HBM462.JKCN.863
HBM258.HQCL.349
HBM749.MTJC.865
HBM935.WLRT.589
HBM899.KTQM.246
HBM433.PPZJ.377
HBM527.BMGW.552
HBM976.LDTR.982
HBM965.PSNC.855
HBM334.DWWF.436
HBM466.XSKL.867
HBM622.STKS.394
HBM699.XBTD.684
HBM842.DDTX.473
HBM222.VQSW.335
HBM568.NGPL.345
HBM875.SBHJ.939
HBM736.MNMD.453
HBM924.VZKC.957
HBM834.THPC.928
HBM554.DSLR.887
HBM739.HCWP.359
HBM685.MSCQ.978
HBM347.MRTV.333
HBM652.TXVL.374
HBM532.GPWF.535
HBM563.FFQJ.764
HBM683.PNGX.923
HBM592.JGSQ.253
HBM465.STNV.844
HBM462.XQCR.933
HBM749.SMWP.555
HBM573.JMXM.823
HBM964.BVWP.737
HBM628.LKGZ.865
HBM547.SJSK.268
HBM874.GLHT.852
HBM285.VFDT.966
HBM479.GMDK.586
HBM844.HNVJ.589
HBM739.CHRX.338
HBM847.HMFW.947
HBM747.SPWK.779
HBM445.HBRQ.488
HBM525.SJRT.585
HBM565.LSMX.645
HBM949.PLLF.787
HBM288.BBKK.828
HBM824.XGWZ.857
HBM524.KHPH.599
HBM684.TLPQ.738
HBM349.SNLB.893
HBM285.RPBV.676
HBM963.KZKG.549
HBM294.XZLM.256
HBM845.VMSZ.536
HBM493.DHZJ.845
HBM847.MDSJ.826
HBM845.SFMK.942
HBM852.VXGN.375
HBM875.FRMB.667
HBM468.ZZVX.652
HBM694.NXCN.368
HBM842.TBXT.532
HBM735.ZMBG.672
HBM827.VSPC.775
HBM634.ZSHF.736
HBM266.FTJN.632
HBM764.ZFGN.389
HBM634.GHKQ.553
HBM344.QRJX.878
HBM267.GLTT.762
HBM785.FJVT.469
HBM692.MHPM.997
HBM835.DNQC.492
HBM247.HLXR.494
HBM985.RCMM.733
HBM844.KXXX.692
HBM983.RHMG.725
HBM599.WCGN.978
HBM349.CWPK.258
HBM745.HTBD.332
HBM298.XPFQ.827
HBM444.PWKX.639
HBM894.DMKD.525
HBM482.DKQF.747
HBM726.GNCK.634
HBM573.TTLG.748
HBM447.KCHB.778
HBM895.RCSZ.274
HBM226.HRTZ.874
HBM293.NNSQ.773
HBM864.CWHJ.963
HBM269.LCND.454
HBM993.ZNNJ.876
HBM256.CJVZ.757
HBM938.GBST.823
HBM347.LCMZ.227
HBM679.NNNK.283
HBM247.KWKL.324
HBM834.SLQN.292
HBM742.NHHQ.357
HBM334.QWFV.953
HBM633.LLDZ.679
HBM744.FNLN.846
HBM696.FGSV.776
HBM865.VDXC.862
HBM449.QGGL.994
HBM368.ZTJH.378
HBM488.CNNZ.544
HBM823.RJNG.364
HBM888.CHTX.783
HBM722.TVXP.469
HBM792.FFJT.499
HBM795.RNJG.329
HBM232.MBNR.586
HBM968.TKLP.596
HBM976.ZTXZ.422
HBM456.GRCM.369
HBM469.ZSKB.898
HBM537.MVDQ.934
HBM949.XCRM.573
HBM265.NQCH.947
HBM974.RQNL.845
HBM528.KNCB.488
HBM242.LSCK.393
HBM238.GTNW.259
HBM436.XFFT.833
HBM284.SBPR.357
HBM236.KSJH.889
HBM876.HTRX.668
HBM852.NKST.623
HBM988.XDFD.773
HBM894.MXVF.534
HBM339.FPMK.994
HBM774.TGWX.478
HBM752.KZCK.589
HBM384.LLDR.794
HBM324.FKLK.233
HBM827.SJBP.777
HBM459.KCST.593
HBM883.PHQS.523
HBM779.FQMX.497
HBM628.QKGB.497
HBM478.VWXX.362
HBM688.FLJB.475
HBM727.DWPV.852
HBM632.WVCH.348
HBM573.MWDW.928
HBM925.KWDZ.229
HBM597.PBJW.593
HBM247.BVLS.599
HBM462.QLBN.535
HBM569.NBHZ.832
HBM942.NXWW.245
HBM896.XHBT.664
HBM627.KDHD.293
HBM464.QLTL.574
HBM373.HCFG.722
HBM759.CHJW.244
HBM255.NWHK.947
HBM388.BLRJ.658
HBM246.KBZS.276
HBM747.TCHW.829
HBM368.HNTH.732
HBM476.VHDB.268
HBM869.HBBF.473
HBM573.SWGH.988
HBM832.ZSQJ.442
HBM876.ZBTD.373
HBM879.GKJM.445
HBM268.RGJT.587
HBM363.CKHC.928
HBM734.LFLC.264
HBM987.KWLK.254
HBM234.FMQW.858
HBM596.VMRV.644
HBM938.KMNW.825
HBM982.THGM.772
HBM943.DFKN.947
HBM775.CMGG.464
HBM647.QDBG.936
HBM363.NTWP.766
HBM235.VKNJ.237
HBM967.LPHM.957
HBM823.CNRW.484
HBM587.QDFJ.926
HBM943.LMMD.654
HBM986.KFWG.239
HBM238.ZKPC.934
HBM958.RMDR.582
HBM443.LGZK.435
HBM297.MZZX.824
HBM265.FQWZ.384
HBM949.ZHRT.229
HBM739.ZDLB.526
HBM679.RLJH.432
HBM688.GVRR.228
HBM545.NTKZ.536
HBM675.TZGS.843
HBM482.MCCP.264
HBM243.NBKL.825
HBM242.HNLH.466
HBM446.TBPT.898
HBM766.NZWP.682
HBM592.DXHG.266
HBM772.XXCD.697
HBM539.GJNB.784
HBM464.PXZP.496
HBM449.JXLG.799
HBM232.MLHJ.832
HBM827.MJMM.447
HBM787.XCSX.733
HBM522.VFGB.335
HBM628.XTDP.423
HBM947.GLGL.465
HBM948.GXMD.986
HBM292.GSZL.269
HBM726.SGLJ.852
HBM933.JFFT.692
HBM683.HJQF.753
HBM363.LLBL.252
HBM332.KQWB.454
HBM666.NDQZ.365
HBM979.VMDC.365
HBM363.TBHH.346
HBM575.THQM.284
HBM259.DZXX.383
HBM437.LCSH.956
HBM762.RPDR.282
HBM729.TVMN.534
HBM378.GNLP.786
HBM234.VNGB.747
HBM975.MVDK.648
HBM494.XDQW.356
HBM424.STVV.842
HBM445.DTJZ.223
HBM282.NSXR.732
HBM464.HPLN.254
HBM364.ZLDR.283
HBM447.MNKW.592
HBM634.JHVB.286
HBM937.TWRN.355
HBM745.RQWF.695
HBM538.XQHP.544
HBM573.JGLL.575
HBM482.JGJX.834
HBM252.JLSW.848
HBM758.GVSL.783
HBM388.MPQC.336
HBM475.FWNZ.942
HBM974.CNWK.327
HBM248.VZRB.728
HBM785.XFTT.663
HBM658.VPJK.669
HBM473.QGDG.848
HBM975.FVCG.922
HBM465.ZNVW.226
HBM223.JQLM.452
HBM593.CLXN.573
HBM676.QVGZ.455
HBM485.VKSZ.779
HBM782.HVML.355
HBM745.FJML.722
HBM532.KKRC.477
HBM595.LBXP.486
HBM563.ZTQV.233
HBM892.CCDZ.345
HBM324.XBMF.465
HBM589.DDFR.467
HBM634.QQWF.789
HBM473.FZJS.484
HBM367.SLVS.253

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_27464\2152322658.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hubmap_ids_filtered['hubmap'] = hubmap_ids_filtered['dataset_id'].apply(lambda d: try_hubmap_id(d))

,portal,dataset_id,organ_name,uuid,hubmap
16039,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01002,no hubmap_id found
16040,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01007,no hubmap_id found
16041,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01014,no hubmap_id found
16042,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01020,no hubmap_id found
16043,HuBMAP,https://doi.org/10.1016/j.cell.2022.12.028#CRC...,large intestine,j.cell.2022.12.028#CRC01025,no hubmap_id found
...,...,...,...,...,...
20565,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney,fe0ded5fc0355c95239f9c040dd31e99,HBM324.XBMF.465
20576,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney,fee4cf0e7da557d3ef5c535b5417ed7a,HBM589.DDFR.467
20577,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney,feea9accbe57b7a052563895ac543d91,HBM634.QQWF.789
20580,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,large intestine,ff5d0d740fea8963e91f2e35c0a85596,HBM473.FZJS.484
20584,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,urinary bladder,ffade7fd19cebd25cd9a9fab2111cb09,HBM367.SLVS.253

In [12]:
# adjust column names
hubmap_ids_filtered.rename(columns={'hubmap': 'hubmap_id'}, inplace=True)
hubmap_ids_filtered_export = hubmap_ids_filtered[hubmap_ids_filtered['hubmap_id'].str.contains('HBM')]
hubmap_ids_filtered_export

C:\Users\abueckle\AppData\Local\Temp\1\ipykernel_27464\2411595670.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hubmap_ids_filtered.rename(columns={'hubmap': 'hubmap_id'}, inplace=True)

,portal,dataset_id,organ_name,uuid,hubmap_id
16251,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney,0027cb59bcb4a34d5db83acaf934a9d9,HBM465.RKKK.264
16253,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney,00318be0b7cfa3c6ed7fbeab08fe700b,HBM232.FHDF.343
16259,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,heart,007f3dfaaa287d5c7c227651f61a9c5b,HBM927.DZCV.762
16265,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,spleen,00d1a3623dac388773bc7780fcb42797,HBM556.KSFB.592
16272,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney,0110be17631ab95c722d476145feb00c,HBM699.GZNP.474
...,...,...,...,...,...
20565,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney,fe0ded5fc0355c95239f9c040dd31e99,HBM324.XBMF.465
20576,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,left kidney,fee4cf0e7da557d3ef5c535b5417ed7a,HBM589.DDFR.467
20577,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,right kidney,feea9accbe57b7a052563895ac543d91,HBM634.QQWF.789
20580,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,large intestine,ff5d0d740fea8963e91f2e35c0a85596,HBM473.FZJS.484
20584,HuBMAP,https://entity.api.hubmapconsortium.org/entiti...,urinary bladder,ffade7fd19cebd25cd9a9fab2111cb09,HBM367.SLVS.253

In [13]:
# export
hubmap_ids_filtered_export.to_csv(
    'output/hubmap_ids_hra-pop_atlas.csv', index=False)