In [27]:
%pip install requests hra_api_client

Requirement already satisfied: requests in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (2.32.3)
Requirement already satisfied: hra_api_client in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (0.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (2025.1.31)
Requirement already satisfied: pydantic>=2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from hra_api_client) (2.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from hra_api_client) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.7.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from hra_api_client) (4.13.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pydantic>=2->hra_api_client) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pydantic>=2->hra_api_client) (2.27.2)
Requirement already satisfied: six>=1.5 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from python-dateutil>=2.8.2->hra_api_client) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
import pandas as pd
import os
import collections

In [29]:
dataframes = []
csv_folder = 'csv'

for file in os.listdir('csv'):
    print(file)
    if file.endswith('.csv'):
        df = pd.read_csv(os.path.join(csv_folder, file))
        df['organ'] = file[:-4]
        dataframes.append(df)

total_df = pd.concat(dataframes)

3d-allen-f-brain.csv
3d-allen-m-brain.csv
3d-nih-f-lymph-node.csv
3d-nih-m-lymph-node.csv
3d-sbu-f-large-intestine.csv
3d-sbu-m-large-intestine.csv
3d-vh-f-blood-vasculature.csv
3d-vh-f-eye-l.csv
3d-vh-f-eye-r.csv
3d-vh-f-fallopian-tube-l.csv
3d-vh-f-fallopian-tube-r.csv
3d-vh-f-heart.csv
3d-vh-f-kidney-l.csv
3d-vh-f-kidney-r.csv
3d-vh-f-knee-l.csv
3d-vh-f-knee-r.csv
3d-vh-f-larynx.csv
3d-vh-f-liver.csv
3d-vh-f-lung.csv
3d-vh-f-main-bronchus.csv
3d-vh-f-mammary-gland-l.csv
3d-vh-f-mammary-gland-r.csv
3d-vh-f-manubrium.csv
3d-vh-f-ovary-l.csv
3d-vh-f-ovary-r.csv
3d-vh-f-palatine-tonsil-l.csv
3d-vh-f-palatine-tonsil-r.csv
3d-vh-f-pancreas.csv
3d-vh-f-pelvis.csv
3d-vh-f-placenta-full-term.csv
3d-vh-f-renal-pelvis-l.csv
3d-vh-f-renal-pelvis-r.csv
3d-vh-f-small-intestine.csv
3d-vh-f-spinal-cord.csv
3d-vh-f-spleen.csv
3d-vh-f-sternum.csv
3d-vh-f-thymus.csv
3d-vh-f-trachea.csv
3d-vh-f-ureter-l.csv
3d-vh-f-ureter-r.csv
3d-vh-f-urinary-bladder.csv
3d-vh-f-uterus.csv
3d-vh-m-blood-vasculature.csv
3d-vh-m-eye-l.csv
3d-vh-m-eye-r.csv
3d-vh-m-heart.csv
3d-vh-m-kidney-l.csv
3d-vh-m-kidney-r.csv
3d-vh-m-knee-l.csv
3d-vh-m-knee-r.csv
3d-vh-m-larynx.csv
3d-vh-m-liver.csv
3d-vh-m-lung.csv
3d-vh-m-main-bronchus.csv
3d-vh-m-palatine-tonsil-l.csv
3d-vh-m-palatine-tonsil-r.csv
3d-vh-m-pancreas.csv
3d-vh-m-pelvis.csv
3d-vh-m-prostate.csv
3d-vh-m-renal-pelvis-l.csv
3d-vh-m-renal-pelvis-r.csv
3d-vh-m-small-intestine.csv
3d-vh-m-spinal-cord.csv
3d-vh-m-spleen.csv
3d-vh-m-thymus.csv
3d-vh-m-trachea.csv
3d-vh-m-ureter-l.csv
3d-vh-m-ureter-r.csv
3d-vh-m-urinary-bladder.csv

## Set global variables

In [30]:
# Get utilities.py
%run ../../shared/utilities.py

In [31]:
# set hra-pop version
# hra_pop_version = "v0.11.1"
hra_pop_version = "v1.0"
branch = 'main'

## Load data

In [32]:
df_y = pd.read_csv(f"https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/{branch}/output-data/{hra_pop_version}/reports/atlas/validation-v7-y-axis.csv")

In [33]:
df_y

,sex,rui_location,dataset,tool,predicted_rui,similarity
0,Female,http://purl.org/ccf/1.5/52c4948d-bdc2-4201-a99...,https://entity.api.hubmapconsortium.org/entiti...,azimuth,http://purl.org/ccf/1.5/72ea5aad-4be7-4478-afc...,0.902167
1,Female,http://purl.org/ccf/1.5/6f74a57b-41ce-4581-a20...,https://entity.api.hubmapconsortium.org/entiti...,azimuth,http://purl.org/ccf/1.5/72ea5aad-4be7-4478-afc...,0.983309
2,Male,http://purl.org/ccf/1.5/0b234d74-b8f9-449f-841...,https://entity.api.sennetconsortium.org/entiti...,celltypist,http://purl.org/ccf/1.5/91f131f5-724b-455e-a2d...,0.991906
3,Male,http://purl.org/ccf/1.5/3177d8d7-3b26-4aa3-998...,https://entity.api.hubmapconsortium.org/entiti...,popv,http://purl.org/ccf/1.5/63b2f5a9-5914-4c45-923...,0.999403
4,Male,http://purl.org/ccf/1.5/5c798396-639b-4964-9a9...,https://entity.api.hubmapconsortium.org/entiti...,celltypist,http://purl.org/ccf/1.5/20a0c365-6a97-4224-ae1...,0.991696
...,...,...,...,...,...,...
1051,Female,http://purl.org/ccf/1.5/502166ab-e841-4b65-904...,https://api.cellxgene.cziscience.com/dp/v1/col...,celltypist,http://purl.org/ccf/1.5/ca476545-5b98-476c-b2f...,0.939912
1052,Male,http://purl.org/ccf/1.5/6f7f3ddd-9889-4bad-8bf...,https://entity.api.sennetconsortium.org/entiti...,celltypist,http://purl.org/ccf/1.5/aba1ebe3-af18-40cc-b53...,0.660448
1053,Male,http://purl.org/ccf/1.5/760368bf-6b4c-4d92-aa2...,https://api.cellxgene.cziscience.com/dp/v1/col...,azimuth,http://purl.org/ccf/1.5/ce5f3bd0-f091-49fe-8fe...,0.897389
1054,Male,http://purl.org/ccf/1.5/79a10f00-84e0-4b8e-862...,https://entity.api.hubmapconsortium.org/entiti...,celltypist,http://purl.org/ccf/1.5/6f89860a-30df-4b79-8e6...,0.813314
1055,Male,http://purl.org/ccf/1.5/87be07c9-cf37-4001-a58...,https://entity.api.hubmapconsortium.org/entiti...,azimuth,http://purl.org/ccf/1.5/7f7fe1b0-d9f6-48c2-a30...,0.843604

## Intersection meshes

In [34]:
total_df = total_df.reset_index()
total_df

,index,source,target,distance,organ
0,0,Allen_cingulate_gyrus_caudal_posterior_part_L,Allen_paracentral_lobule_rostral_part_L,-1,3d-allen-f-brain
1,1,Allen_body_of_lateral_ventricle_L,Allen_thalamus_L,-1,3d-allen-f-brain
2,2,Allen_parietal_operculum_L,Allen_planum_temporale_L,-1,3d-allen-f-brain
3,3,Allen_body_of_caudate_L,Allen_white_matter_of_forebrain_L,-1,3d-allen-f-brain
4,4,Allen_long_insular_gyri_L,Allen_white_matter_of_forebrain_L,-1,3d-allen-f-brain
...,...,...,...,...,...
1996,5,VH_M_trigone_of_urinary_bladder,VH_M_ureteral_orifice_R,-1,3d-vh-m-urinary-bladder
1997,6,VH_M_fundus_of_urinary_bladder_dome,VH_M_ureteral_orifice_R,-1,3d-vh-m-urinary-bladder
1998,7,VH_M_fundus_of_urinary_bladder_base1,VH_M_ureteral_orifice_L,-1,3d-vh-m-urinary-bladder
1999,8,VH_M_fundus_of_urinary_bladder_dome,VH_M_ureteral_orifice_L,-1,3d-vh-m-urinary-bladder
2000,9,VH_M_fundus_of_urinary_bladder_base1,VH_M_urinary_bladder_neck_smooth_muscle,-1,3d-vh-m-urinary-bladder

### clean

In [35]:
total_df = total_df.drop(['index', 'distance'], axis=1)

In [36]:
# initialize dict for result

collision_counter = collections.defaultdict(set)

base_url_extraction_site = "https://apps.humanatlas.io/api/v1/extraction-site?iri="

# get extraction site IRIs and then get AS intersections from HRA API
for iri in df_y['rui_location']:

  # get extraction site
  extraction_site = ""

  response = requests.get(base_url_extraction_site+iri)

  if response:
    extraction_site = json.loads(response.text)
  else:
    raise Exception(f"Non-success status code: {response.status_code}")

  # send extraction site to /collisions endpoints
  collisions = api_instance.collisions(extraction_site)

  for item in collisions:
    collision_counter[item['node_name']].add(iri)

In [37]:
collision_counter

defaultdict(set,
            {'VH_F_renal_papilla_L_h': {'http://purl.org/ccf/1.5/52c4948d-bdc2-4201-a991-61a2c0a565c0'},
             'VH_F_renal_pyramid_L_h': {'http://purl.org/ccf/1.5/52c4948d-bdc2-4201-a991-61a2c0a565c0'},
             'VH_F_renal_papilla_R_i': {'http://purl.org/ccf/1.5/6f74a57b-41ce-4581-a206-2e84b58c1c98'},
             'VH_F_renal_pyramid_R_i': {'http://purl.org/ccf/1.5/6f74a57b-41ce-4581-a206-2e84b58c1c98'},
             'VH_M_right_anterior_basal_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/0b234d74-b8f9-449f-8416-ef10e33d2f7f'},
             'VH_M_right_anterior_basal_bronchus': {'http://purl.org/ccf/1.5/0b234d74-b8f9-449f-8416-ef10e33d2f7f'},
             'VH_M_cartilage_of_the_tertiary_bronchus_R': {'http://purl.org/ccf/1.5/0b234d74-b8f9-449f-8416-ef10e33d2f7f',
              'http://purl.org/ccf/1.5/91f131f5-724b-455e-a2d7-cade7eae4be9',
              'http://purl.org/ccf/1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0'},
             'VH_M_duodenum_ascending': {'http://purl.org/ccf/1.5/3177d8d7-3b26-4aa3-9984-3c112d461446',
              'http://purl.org/ccf/1.5/42b97dcb-2033-40ea-82a2-319a1e30dca2',
              'http://purl.org/ccf/1.5/75ff443d-c177-4dab-a866-89e9141b73a4',
              'http://purl.org/ccf/1.5/78ee24bb-4ae4-49e9-bad2-d6f13166b89e',
              'http://purl.org/ccf/1.5/8adcc2aa-6d36-4fab-a745-7a097a732768',
              'http://purl.org/ccf/1.5/a1fc9d45-5af9-4fc4-b2be-340ef0716e09',
              'http://purl.org/ccf/1.5/d9aed544-4c6e-42c2-a137-9a9381d8f8c8'},
             'VH_M_duodenum_horizonal': {'http://purl.org/ccf/1.5/3177d8d7-3b26-4aa3-9984-3c112d461446',
              'http://purl.org/ccf/1.5/42b97dcb-2033-40ea-82a2-319a1e30dca2',
              'http://purl.org/ccf/1.5/75ff443d-c177-4dab-a866-89e9141b73a4',
              'http://purl.org/ccf/1.5/78ee24bb-4ae4-49e9-bad2-d6f13166b89e',
              'http://purl.org/ccf/1.5/a1fc9d45-5af9-4fc4-b2be-340ef0716e09',
              'http://purl.org/ccf/1.5/d9aed544-4c6e-42c2-a137-9a9381d8f8c8'},
             'VH_M_heart_right_ventricle': {'http://purl.org/ccf/1.5/5c798396-639b-4964-9a91-501b42d23d6f',
              'http://purl.org/ccf/1.5/ce5f3bd0-f091-49fe-8fe5-67004848078b',
              'http://purl.org/ccf/1.5/f1790d4b-bbc0-434c-b8ed-f21e8b8be903',
              'http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b345-dbe4975966fd'},
             'VH_M_interventricular_septum': {'http://purl.org/ccf/1.5/5c798396-639b-4964-9a91-501b42d23d6f',
              'http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b345-dbe4975966fd'},
             'VH_M_heart_left_ventricle': {'http://purl.org/ccf/1.5/118235b7-38a4-4fcf-8834-bad5765f5eeb',
              'http://purl.org/ccf/1.5/20a0c365-6a97-4224-ae14-16fba10c13f8',
              'http://purl.org/ccf/1.5/3156203b-0238-447d-9aae-c4341f2da943',
              'http://purl.org/ccf/1.5/39e72b20-77e5-45a5-bb0e-f374ea5894ad',
              'http://purl.org/ccf/1.5/5c798396-639b-4964-9a91-501b42d23d6f',
              'http://purl.org/ccf/1.5/5cb72454-f0fb-41d5-9cad-5797e1b447ae',
              'http://purl.org/ccf/1.5/760368bf-6b4c-4d92-aa2b-24e17fd947d3',
              'http://purl.org/ccf/1.5/87df967f-1311-43ac-a306-04e47d2f4a60',
              'http://purl.org/ccf/1.5/886e391d-0151-46d3-8a51-084bf6a06910',
              'http://purl.org/ccf/1.5/a0ff0780-d666-42fe-8068-a3b41b1c6aa0',
              'http://purl.org/ccf/1.5/da28394d-789a-4fba-842a-f8ba5046b221',
              'http://purl.org/ccf/1.5/de8bd0bf-7765-44c4-9d22-5ff5c0586816',
              'http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b345-dbe4975966fd'},
             'VH_F_ileum': {'http://purl.org/ccf/1.5/4af4b1bd-c71d-4ade-a9f6-47b2ccc9f5bb',
              'http://purl.org/ccf/1.5/7f4ad752-8a2d-4088-b91e-4e0d1a724d98',
              'http://purl.org/ccf/1.5/d8c8faa2-7e2a-4b74-9531-cd08be659c10',
              'http://purl.org/ccf/1.5/e07ea320-ff6e-4f05-a2a0-75ae2e966ef7'},
             'VH_F_ileum_terminal': {'http://purl.org/ccf/1.5/4af4b1bd-c71d-4ade-a9f6-47b2ccc9f5bb',
              'http://purl.org/ccf/1.5/7f4ad752-8a2d-4088-b91e-4e0d1a724d98',
              'http://purl.org/ccf/1.5/d8c8faa2-7e2a-4b74-9531-cd08be659c10'},
             'VH_F_right_posterior_basal_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/6f7f3ddd-9889-4bad-8bfc-8340c7b6af8b'},
             'VH_M_renal_pyramid_L_i': {'http://purl.org/ccf/1.5/37283102-d963-4639-8834-4813fbb3c247'},
             'VH_M_left_lateral_basal_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/38d89d1c-002c-4bd3-a178-9af62b112834'},
             'VH_M_cartilage_of_the_tertiary_bronchus_L': {'http://purl.org/ccf/1.5/2cf1885a-9b6f-440c-9f60-443d5dd3c8ba',
              'http://purl.org/ccf/1.5/38d89d1c-002c-4bd3-a178-9af62b112834',
              'http://purl.org/ccf/1.5/c9e06f93-152f-4c72-aa69-4b1176833af7'},
             'VH_M_left_posetrior_basal_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/049f27a1-1e84-4f8a-a47e-48a0879b8652',
              'http://purl.org/ccf/1.5/38d89d1c-002c-4bd3-a178-9af62b112834',
              'http://purl.org/ccf/1.5/f876a7c0-7fcb-4cd4-97d7-639194f5a1af',
              'http://purl.org/ccf/1.5/fb73e18b-9ddc-4fdf-b9a6-4b7735e5017b'},
             'VH_M_left_medial_basal_bronchus': {'http://purl.org/ccf/1.5/38d89d1c-002c-4bd3-a178-9af62b112834'},
             'VH_M_left_anterior_basal_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/38d89d1c-002c-4bd3-a178-9af62b112834'},
             'VH_M_left_medial_basal_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/38d89d1c-002c-4bd3-a178-9af62b112834'},
             'VH_M_skin': {'http://purl.org/ccf/1.5/314450f7-0477-4152-b4d6-cb474cbc0cd7',
              'http://purl.org/ccf/1.5/56d63930-60f2-49f5-a3bb-afc8d865c152',
              'http://purl.org/ccf/1.5/830da174-80d2-436e-ae02-4e36a3eedd43',
              'http://purl.org/ccf/1.5/8cde177e-fbbd-434f-b04d-271dd38f286a',
              'http://purl.org/ccf/1.5/c8f471f9-e052-4a00-b145-b299b97ed960',
              'http://purl.org/ccf/1.5/cce37703-e4e8-454c-a0c4-4ff58652ab8f',
              'http://purl.org/ccf/1.5/d16014ad-8b92-487b-bca7-044d3d745dba',
              'http://purl.org/ccf/1.5/fcfcc65b-f91f-4447-a29b-c9836104570c',
              'http://purl.org/ccf/1.5/ff034c0c-a625-48b8-891c-857e556db1c4'},
             'VH_M_right_medial_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/d662fd53-e925-4921-8d8b-bc91eed1519b',
              'http://purl.org/ccf/1.5/f15f5400-2ef9-45fc-bf0f-72f14d6f8f9e'},
             'VH_M_renal_column_R': {'http://purl.org/ccf/1.5/57bab703-98bd-4106-9160-af951a74e4df',
              'http://purl.org/ccf/1.5/df0b33f7-371a-47a4-a636-a27db19bdbc9'},
             'VH_M_outer_cortex_of_kidney_R': {'http://purl.org/ccf/1.5/5c7d77e3-e7e4-4f6c-bf86-01e78c3de7ad',
              'http://purl.org/ccf/1.5/6a6392a9-8ac1-4666-a684-83d310ca055f',
              'http://purl.org/ccf/1.5/769ca7e9-ead0-4882-966c-d6f5c273c2ee',
              'http://purl.org/ccf/1.5/cb68d9a5-9884-4eef-afe8-e087cac7bf54',
              'http://purl.org/ccf/1.5/db35f27d-313f-4dd6-819b-375cf106aac1',
              'http://purl.org/ccf/1.5/decfd5b4-07de-4894-bc83-6698cfb1ef8c',
              'http://purl.org/ccf/1.5/df0b33f7-371a-47a4-a636-a27db19bdbc9'},
             'VH_M_outer_cortex_of_kidney_L': {'http://purl.org/ccf/1.5/2990ecc8-1854-4794-8f11-1b31c5c94e5f',
              'http://purl.org/ccf/1.5/5166a7a1-bd21-4aa3-ba20-23453cb4c431',
              'http://purl.org/ccf/1.5/7f7fe1b0-d9f6-48c2-a304-2ea5874c7392',
              'http://purl.org/ccf/1.5/87be07c9-cf37-4001-a589-e2c048b5d3f3',
              'http://purl.org/ccf/1.5/c07ec91d-9dbe-4132-a93c-b960895b009d',
              'http://purl.org/ccf/1.5/cf4ba102-edf7-4fe4-bb1d-860cdf57609d',
              'http://purl.org/ccf/1.5/f31c1726-c693-4734-8c1c-4f1d64bbe034',
              'http://purl.org/ccf/1.5/f3f2fabb-6802-4fd4-920e-1914293db252'},
             'VH_M_left_lateral_basal_bronchus': {'http://purl.org/ccf/1.5/2cf1885a-9b6f-440c-9f60-443d5dd3c8ba'},
             'VH_M_right_cardiac_atrium': {'http://purl.org/ccf/1.5/3bf6e5a0-a04d-498e-89b1-b2c2562e4483',
              'http://purl.org/ccf/1.5/f6512db4-2809-4ffe-864d-ace61789dff6'},
             'VH_M_right_anterior_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/91f131f5-724b-455e-a2d7-cade7eae4be9'},
             'VH_M_right_apical_bronchus': {'http://purl.org/ccf/1.5/91f131f5-724b-455e-a2d7-cade7eae4be9'},
             'VH_M_fundus_of_urinary_bladder_dome': {'http://purl.org/ccf/1.5/b2aca02c-9559-4869-b551-4bfb59bf84b3'},
             'VH_M_jejunum': {'http://purl.org/ccf/1.5/502f175c-9d55-4341-b6ff-0f04d76522d5',
              'http://purl.org/ccf/1.5/79a10f00-84e0-4b8e-8622-485973df3773',
              'http://purl.org/ccf/1.5/8023d0ab-338a-43c4-9f9b-d637220f1b8e',
              'http://purl.org/ccf/1.5/8adcc2aa-6d36-4fab-a745-7a097a732768',
              'http://purl.org/ccf/1.5/bddd9066-3f8c-4330-8e33-23be89ee8a0b',
              'http://purl.org/ccf/1.5/ea1d468d-e988-42cd-8e34-71701e568878',
              'http://purl.org/ccf/1.5/fd76b9bb-85b0-4dd0-8e60-7c6ec7c95d73'},
             'VH_F_outer_cortex_of_kidney_L': {'http://purl.org/ccf/1.5/007eb4d9-1694-4380-99e1-4aba832d9227',
              'http://purl.org/ccf/1.5/2ba5b803-1162-4a7e-9371-e1c445deb97f',
              'http://purl.org/ccf/1.5/8d126897-60f6-433e-a56b-cbe730475742',
              'http://purl.org/ccf/1.5/bd004aeb-6e60-4d5b-8d40-cfdd55b8b6fe',
              'http://purl.org/ccf/1.5/e88dfa31-cb6b-4eaa-b16c-e5c97de2701e',
              'http://purl.org/ccf/1.5/fd380a0c-2915-4d73-b3f4-d161badbaccb'},
             'VH_F_renal_pyramid_L_b': {'http://purl.org/ccf/1.5/8f99a469-7d51-46dc-919d-2e002eeae868'},
             'VH_M_ureter_L': {'http://purl.org/ccf/1.5/19fee435-ebad-476c-bc9a-e11d2cee035e',
              'http://purl.org/ccf/1.5/1f414fc5-cb93-45b7-a1b8-0cd21dfa9f7d',
              'http://purl.org/ccf/1.5/3a25960a-8e7a-4020-8dfb-8ce6c3423e35',
              'http://purl.org/ccf/1.5/76c494e3-ed44-4cd6-a634-e83b02bcd767'},
             'VH_M_right_lateral_bronchus': {'http://purl.org/ccf/1.5/594902fb-c4c1-47c3-b98e-3101b93a73e4',
              'http://purl.org/ccf/1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0'},
             'VH_F_fat_L': {'http://purl.org/ccf/1.5/d8ed19a3-2960-472f-a1ed-189cdbb71fdc'},
             'VH_F_mammary_lobes_L': {'http://purl.org/ccf/1.5/d8ed19a3-2960-472f-a1ed-189cdbb71fdc'},
             'VH_F_main_lactiferous_ducts_L': {'http://purl.org/ccf/1.5/d8ed19a3-2960-472f-a1ed-189cdbb71fdc'},
             'VH_F_suspensory_ligaments_L': {'http://purl.org/ccf/1.5/d8ed19a3-2960-472f-a1ed-189cdbb71fdc'},
             'VH_M_ureter_R': {'http://purl.org/ccf/1.5/ca23f77c-a3cd-453f-bbe9-2d8d1514fc8e'},
             'VH_F_lingula_superior_bronchopulmonary_segment': {'http://purl.org/ccf/1.5/50709361-c670-4ccf-9322-e65b57b3ea8f'},
             'VH_F_duodenum_descending': {'http://purl.org/ccf/1.5/5fa952b1-a5a7-4089-bdc2-7208f71f45be',
              'http://purl.org/ccf/1.5/65f3b03b-1eb1-487d-8c02-c4d107cc9400',
              'http://purl.org/ccf/1.5/d1085194-4902-4252-95fd-faf03afd9288'},
             'VH_M_trigone_of_urinary_bladder': {'http://purl.org/ccf/1.5/0060612c-6d95-47d8-a8d0-0443fff344e9',
              'http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1b4-618af0b79d4c',
              'http://purl.org/ccf/1.5/c0d63695-e48e-44c1-a1a3-db138d1f80d1'},
             'VH_M_fundus_of_urinary_bladder_base1': {'http://purl.org/ccf/1.5/0060612c-6d95-47d8-a8d0-0443fff344e9',
              'http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1b4-618af0b79d4c',
              'http://purl.org/ccf/1.5/c0d63695-e48e-44c1-a1a3-db138d1f80d1'},
             'VH_M_ascending_colon': {'http://purl.org/ccf/1.5/37248725-6ed5-4589-ac5a-9951d1a783e7',
              'http://purl.org/ccf/1.5/3b2cb9ee-2a6f-4fb3-bc1b-dbd192d3163c',
              'http://purl.org/ccf/1.5/3c695f26-b7ed-44ad-8e11-894932defa86',
              'http://purl.org/ccf/1.5/5df04f61-5fcc-4035-92c3-631f772a6ce0',
              'http://purl.org/ccf/1.5/615aa60c-0a0a-4614-bae2-f85112479919',
              'http://purl.org/ccf/1.5/8e8d9121-3a47-4c89-9e63-aec6659075d2',
              'http://purl.org/ccf/1.5/91009a1d-ddea-4489-af88-3e32ca47cde7',
              'http://purl.org/ccf/1.5/99ac7242-14d9-4efe-b6d9-b44cab80d84d'},
             'VH_M_caecum': {'http://purl.org/ccf/1.5/615aa60c-0a0a-4614-bae2-f85112479919',
              'http://purl.org/ccf/1.5/99ac7242-14d9-4efe-b6d9-b44cab80d84d'},
             'VH_F_ileocecal_valve': {'http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a806-a113c1a1a478'},
             'VH_F_caecum': {'http://purl.org/ccf/1.5/3425fa0c-c5cb-4493-b6ba-41520334b13e',
              'http://purl.org/ccf/1.5/48f6aab3-8d58-4675-806c-3fd7d5b7336f',
              'http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a806-a113c1a1a478'},
             'VH_F_ascending_colon': {'http://purl.org/ccf/1.5/3425fa0c-c5cb-4493-b6ba-41520334b13e',
              'http://purl.org/ccf/1.5/48f6aab3-8d58-4675-806c-3fd7d5b7336f',
              'http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a806-a113c1a1a478'},
             'VH_F_hepatic_flexure_of_colon': {'http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a806-a113c1a1a478'},
             'VH_F_transverse_colon': {'http://purl.org/ccf/1.5/43e195fb-0f50-4b67-bff1-b74f68290fc6',
              'http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a806-a113c1a1a478',
              'http://purl.org/ccf/1.5/db4f3eca-e9f8-4f9c-88a1-795a20dd0f84'},
             'VH_F_renal_pyramid_R_a': {'http://purl.org/ccf/1.5/f66f91f9-c6c5-414d-b784-2faec33e0505'},
             'VH_F_renal_column_R': {'http://purl.org/ccf/1.5/f66f91f9-c6c5-414d-b784-2faec33e0505'},
             'VH_M_diaphragmatic_surface_of_spleen': {'http://purl.org/ccf/1.5/32aa316e-7b68-4d4e-ac4d-4194787529ea',
              'http://purl.org/ccf/1.5/373c77e0-1d77-4c28-b547-0eb9420f30bc',
              'http://purl.org/ccf/1.5/b5efb4f3-6dee-4a3c-b55f-91e6c40c6003',
              'http://purl.org/ccf/1.5/e21afc3c-3a7c-4717-90d5-e5739fd8432c'},
             'VH_F_left_posterior_basal_bronchus': {'http://purl.org/ccf/1.5/72bf1a62-eccf-4fdd-9ba4-270410e9a359'},
             'VH_F_cartilage_of_tertiary_bronchus_L': {'http://purl.org/ccf/1.5/72bf1a62-eccf-4fdd-9ba4-270410e9a359'},
             'VH_F_left_cardiac_atrium': {'http://purl.org/ccf/1.5/502166ab-e841-4b65-9045-7c386166a9e8'},
             'VH_F_left_ventricle': {'http://purl.org/ccf/1.5/04baf323-eda0-4f72-bea1-aa943aa70894',
              'http://purl.org/ccf/1.5/05c11830-1526-4472-bd12-ea24dbcfd3cc',
              'http://purl.org/ccf/1.5/16e98d8c-8983-48c2-bb41-7b1cfbbf2e4a',
              'http://purl.org/ccf/1.5/2156f837-2ab2-4305-8e7f-8084249e91cd',
              'http://purl.org/ccf/1.5/2816c343-c908-45bf-8964-974b1c54a5b9',
              'http://purl.org/ccf/1.5/9abfed4e-2fde-4d80-a8aa-7439a106d895',
              'http://purl.org/ccf/1.5/adb13ed6-5236-419c-b9c1-c516f3c7471d',
              'http://purl.org/ccf/1.5/e13cd910-c2df-4b83-ad68-2e7409089fa4'},
             'VH_F_right_cardiac_atrium': {'http://purl.org/ccf/1.5/ca476545-5b98-476c-b2fd-1b8e1708faed',
              'http://purl.org/ccf/1.5/df2e5e19-48af-46b1-aa9a-84bfcaa9415a'},
             'VH_M_ileum_terminal': {'http://purl.org/ccf/1.5/27c90961-5430-4217-ad97-4feaa91cede7',
              'http://purl.org/ccf/1.5/5df42986-8bb8-4715-93ac-a1ac2daec853',
              'http://purl.org/ccf/1.5/6f055461-adb2-41fe-86c1-50d3afdf9360',
              'http://purl.org/ccf/1.5/6f89860a-30df-4b79-8e6d-dd209c959374',
              'http://purl.org/ccf/1.5/6fe91946-48bb-485f-9ad0-5f0550d1f2b3',
              'http://purl.org/ccf/1.5/b09f5826-e6fa-4bec-8054-2fb6e6f202ae',
              'http://purl.org/ccf/1.5/e4a44b76-53fd-4c88-9ccf-ba095fcb9673'},
             'VH_M_descending_colon': {'http://purl.org/ccf/1.5/23e9d58a-c93f-414b-baf9-3692ea20fd1c',
              'http://purl.org/ccf/1.5/6bbdd96b-5fae-406c-a0a5-8e20e1bd0d8e',
              'http://purl.org/ccf/1.5/72881a98-7301-412f-8223-dce4b9b5abcd',
              'http://purl.org/ccf/1.5/76a8931b-1c06-4646-8a17-ac7828b6e879',
              'http://purl.org/ccf/1.5/82d414d4-59a7-4a61-9d86-278cb73a3ddd',
              'http://purl.org/ccf/1.5/9a6cb9d5-afdd-429d-98ba-f157a42c7937',
              'http://purl.org/ccf/1.5/ba9d007b-c5c7-4231-80f9-42403a98a6df',
              'http://purl.org/ccf/1.5/fb4cec06-b147-4277-a6cf-8aa21e294183'},
             'VH_M_gastric_impression_of_liver': {'http://purl.org/ccf/1.5/67e5f7e1-7b82-4aff-890e-9f8fc1f5c89b',
              'http://purl.org/ccf/1.5/8eea8795-2c2f-4811-bf19-ceff62be1128'},
             'VH_M_diaphragmatic_surface': {'http://purl.org/ccf/1.5/67e5f7e1-7b82-4aff-890e-9f8fc1f5c89b',
              'http://purl.org/ccf/1.5/8eea8795-2c2f-4811-bf19-ceff62be1128'},
             'VH_M_left_anterolateral_segment': {'http://purl.org/ccf/1.5/67e5f7e1-7b82-4aff-890e-9f8fc1f5c89b',
              'http://purl.org/ccf/1.5/8eea8795-2c2f-4811-bf19-ceff62be1128'},
             'VH_M_liver_capsule': {'http://purl.org/ccf/1.5/67e5f7e1-7b82-4aff-890e-9f8fc1f5c89b',
              'http://purl.org/ccf/1.5/8eea8795-2c2f-4811-bf19-ceff62be1128'},
             'VH_F_jejenum': {'http://purl.org/ccf/1.5/b195f78a-28c0-48d3-8b23-a92d38131d55',
              'http://purl.org/ccf/1.5/d194f593-af76-4ee7-84a6-00f7531d47cf',
              'http://purl.org/ccf/1.5/dac50a34-5b99-4f66-9623-7d800ed63be1',
              'http://purl.org/ccf/1.5/e240c0a4-5e53-4464-8320-ad775f2c4bf7'},
             'VH_F_duodenum_ascending': {'http://purl.org/ccf/1.5/4ecffbfc-dc50-4140-95e8-4f97d5804f4f',
              'http://purl.org/ccf/1.5/74c8746d-be53-493d-9a2a-1edbe24f0d16',
              'http://purl.org/ccf/1.5/9d795171-ba1f-4ae2-9b98-9a285280ebf6',
              'http://purl.org/ccf/1.5/dac50a34-5b99-4f66-9623-7d800ed63be1'},
             'VH_F_left_ureter': {'http://purl.org/ccf/1.5/5764d42e-95e4-4e5a-b36e-ca498354906d',
              'http://purl.org/ccf/1.5/c5e652ed-7e40-41de-bfc0-a73f05a0c66a'},
             'VH_F_hilum_of_spleen': {'http://purl.org/ccf/1.5/6febbcea-502d-466e-bb26-6e3eb8240902',
              'http://purl.org/ccf/1.5/fa9ecb7f-16d5-4733-bc89-46496a9e886e'},
             'VH_F_renal_column_L': {'http://purl.org/ccf/1.5/26edd761-8b50-453c-9b03-2337806c9e3a',
              'http://purl.org/ccf/1.5/2ba5b803-1162-4a7e-9371-e1c445deb97f',
              'http://purl.org/ccf/1.5/70ad7ae6-c9af-4975-98e2-98c249e36ddd',
              'http://purl.org/ccf/1.5/bd004aeb-6e60-4d5b-8d40-cfdd55b8b6fe',
              'http://purl.org/ccf/1.5/fd380a0c-2915-4d73-b3f4-d161badbaccb'},
             'VH_F_renal_pyramid_L_f': {'http://purl.org/ccf/1.5/70ad7ae6-c9af-4975-98e2-98c249e36ddd',
              'http://purl.org/ccf/1.5/731ade72-cdb7-4262-8be1-859396820dfd'},
             'VH_F_sigmoid_colon': {'http://purl.org/ccf/1.5/79aded5b-cbd0-494d-9534-7ec8292fa0ab',
              'http://purl.org/ccf/1.5/8b652088-8c73-466d-b59c-3fbb8c01e399',
              'http://purl.org/ccf/1.5/93286ce3-669a-4f3f-a85a-7eaaedc15c59',
              'http://purl.org/ccf/1.5/cd304e60-3de4-4dd9-b289-ce1a0efae4d7'},
             'VH_M_duodenum_descending': {'http://purl.org/ccf/1.5/1f53fe4d-d77b-4508-ba36-22b6b3ac0e53',
              'http://purl.org/ccf/1.5/2b38ef86-7e4d-4e27-b9c6-d2015ec49692',
              'http://purl.org/ccf/1.5/470a6b74-a31b-4a50-bfff-da1b475c945b',
              'http://purl.org/ccf/1.5/5d35eae0-82df-40c7-952c-6fbab03034b2',
              'http://purl.org/ccf/1.5/63b2f5a9-5914-4c45-9239-139948a93498',
              'http://purl.org/ccf/1.5/85765dd5-2197-4361-b4c6-c9d30186044a',
              'http://purl.org/ccf/1.5/8adcc2aa-6d36-4fab-a745-7a097a732768'},
             'VH_M_thymus_lobe_L': {'http://purl.org/ccf/1.5/5fb93ab2-0fa8-4583-af2c-c3b8dfeb2a44'},
             'VH_M_thymus_lobe_R': {'http://purl.org/ccf/1.5/5fb93ab2-0fa8-4583-af2c-c3b8dfeb2a44'},

In [38]:
total_df['source_extraction_sites_number'] = total_df['source'].apply(lambda x: collision_counter[x])

In [39]:
total_df['target_extraction_sites_number'] = total_df['target'].apply(lambda x: collision_counter[x])

In [40]:
total_df

,source,target,organ,source_extraction_sites_number,target_extraction_sites_number
0,Allen_cingulate_gyrus_caudal_posterior_part_L,Allen_paracentral_lobule_rostral_part_L,3d-allen-f-brain,{},{}
1,Allen_body_of_lateral_ventricle_L,Allen_thalamus_L,3d-allen-f-brain,{},{}
2,Allen_parietal_operculum_L,Allen_planum_temporale_L,3d-allen-f-brain,{},{}
3,Allen_body_of_caudate_L,Allen_white_matter_of_forebrain_L,3d-allen-f-brain,{},{}
4,Allen_long_insular_gyri_L,Allen_white_matter_of_forebrain_L,3d-allen-f-brain,{},{}
...,...,...,...,...,...
1996,VH_M_trigone_of_urinary_bladder,VH_M_ureteral_orifice_R,3d-vh-m-urinary-bladder,{http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1...,{}
1997,VH_M_fundus_of_urinary_bladder_dome,VH_M_ureteral_orifice_R,3d-vh-m-urinary-bladder,{http://purl.org/ccf/1.5/b2aca02c-9559-4869-b5...,{}
1998,VH_M_fundus_of_urinary_bladder_base1,VH_M_ureteral_orifice_L,3d-vh-m-urinary-bladder,{http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1...,{}
1999,VH_M_fundus_of_urinary_bladder_dome,VH_M_ureteral_orifice_L,3d-vh-m-urinary-bladder,{http://purl.org/ccf/1.5/b2aca02c-9559-4869-b5...,{}
2000,VH_M_fundus_of_urinary_bladder_base1,VH_M_urinary_bladder_neck_smooth_muscle,3d-vh-m-urinary-bladder,{http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1...,{}

In [41]:
total_df['sum_extraction_sites_number'] = total_df.apply(lambda x: len(x['source_extraction_sites_number'] & x['target_extraction_sites_number']), axis=1)

In [42]:
total_df['common_extraction_sites'] = total_df.apply(lambda x: x['source_extraction_sites_number'] & x['target_extraction_sites_number'], axis=1)

In [43]:
total_df = total_df.sort_values(by='sum_extraction_sites_number', ascending=False)

In [44]:
total_df

,source,target,organ,source_extraction_sites_number,target_extraction_sites_number,sum_extraction_sites_number,common_extraction_sites
208,VH_M_rectum,VH_M_sigmoid_colon,3d-sbu-m-large-intestine,{http://purl.org/ccf/1.5/abab52f8-6fd4-4e3f-8f...,{http://purl.org/ccf/1.5/abab52f8-6fd4-4e3f-8f...,6,{http://purl.org/ccf/1.5/abab52f8-6fd4-4e3f-8f...
1906,VH_M_duodenum_ascending,VH_M_duodenum_horizonal,3d-vh-m-small-intestine,{http://purl.org/ccf/1.5/3177d8d7-3b26-4aa3-99...,{http://purl.org/ccf/1.5/3177d8d7-3b26-4aa3-99...,6,{http://purl.org/ccf/1.5/3177d8d7-3b26-4aa3-99...
500,VH_F_outer_cortex_of_kidney_L,VH_F_renal_column_L,3d-vh-f-kidney-l,{http://purl.org/ccf/1.5/bd004aeb-6e60-4d5b-8d...,{http://purl.org/ccf/1.5/bd004aeb-6e60-4d5b-8d...,3,{http://purl.org/ccf/1.5/2ba5b803-1162-4a7e-93...
1992,VH_M_fundus_of_urinary_bladder_base1,VH_M_trigone_of_urinary_bladder,3d-vh-m-urinary-bladder,{http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1...,{http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1...,3,{http://purl.org/ccf/1.5/1fa8bd4e-49af-4121-a1...
197,VH_F_ascending_colon,VH_F_caecum,3d-sbu-f-large-intestine,{http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a8...,{http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a8...,3,{http://purl.org/ccf/1.5/d76af3c2-3456-48ab-a8...
...,...,...,...,...,...,...,...
1980,VH_M_major_calyx_R_a,VH_M_minor_calyx_R_d,3d-vh-m-ureter-r,{},{},0,{}
1981,VH_M_renal_pelvis_R,VH_M_ureter_R,3d-vh-m-ureter-r,{},{http://purl.org/ccf/1.5/ca23f77c-a3cd-453f-bb...,0,{}
1982,VH_M_major_calyx_R_b,VH_M_minor_calyx_R_i,3d-vh-m-ureter-r,{},{},0,{}
1983,VH_M_minor_calyx_R_f,VH_M_minor_calyx_R_g,3d-vh-m-ureter-r,{},{},0,{}
0,Allen_cingulate_gyrus_caudal_posterior_part_L,Allen_paracentral_lobule_rostral_part_L,3d-allen-f-brain,{},{},0,{}

In [45]:
intersection_space_collision_api = 'http://localhost:8080/get-collisions-intersection-space'

In [46]:
exact_collisions_with_intersection_space = []

for index, row in total_df.iterrows():
    count = 0
    for iri in row['common_extraction_sites']:
        # get extraction site
        extraction_site = ""
        response = requests.get(base_url_extraction_site+iri)

        if response:
            extraction_site = json.loads(response.text)
            extraction_site['pair1'] = row['source']
            extraction_site['pair2'] = row['target']
        else:
            raise Exception(f"Non-success status code: {response.status_code}")

        # send extraction site to /collisions endpoints
        r = requests.post(url=intersection_space_collision_api, json=extraction_site)
        r = r.json()
        if 'result' in r and r['result'] == 1:
            count += 1

    exact_collisions_with_intersection_space.append(count)

total_df['exact_collisions_with_intersection_space'] = exact_collisions_with_intersection_space

ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get-collisions-intersection-space (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000231D39F7020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

In [ ]:
filtered_df = total_df[total_df['exact_collisions_with_intersection_space'] > 0]

In [ ]:
filtered_df

,source,target,organ,source_extraction_sites_number,target_extraction_sites_number,sum_extraction_sites_number,common_extraction_sites,exact_collisions_with_intersection_space
504,VH_M_outer_cortex_of_kidney_L,VH_M_renal_pyramid_L_a,3d-vh-m-kidney-l,{http://purl.org/ccf/1.5/cf4ba102-edf7-4fe4-bb...,{http://purl.org/ccf/1.5/c07ec91d-9dbe-4132-a9...,3,{http://purl.org/ccf/1.5/c07ec91d-9dbe-4132-a9...,3
116,VH_F_kidney_capsule_L,VH_F_outer_cortex_of_kidney_L,3d-vh-f-kidney-l,{http://purl.org/ccf/1.5/2ba5b803-1162-4a7e-93...,{http://purl.org/ccf/1.5/007eb4d9-1694-4380-99...,3,{http://purl.org/ccf/1.5/2ba5b803-1162-4a7e-93...,3
49,VH_M_peripheral_zone_of_prostate_L,VH_M_peripheral_zone_of_prostate_R,3d-vh-m-prostate,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,2,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,1
575,VH_M_heart_right_ventricle,VH_M_interventricular_septum,3d-vh-m-heart,{http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b3...,{http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b3...,2,{http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b3...,2
75,VH_M_central_zone_of_prostate_L,VH_M_peripheral_zone_of_prostate_L,3d-vh-m-prostate,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,2,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,2
560,VH_M_heart_left_ventricle,VH_M_heart_right_ventricle,3d-vh-m-heart,{http://purl.org/ccf/1.5/87df967f-1311-43ac-a3...,{http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b3...,2,{http://purl.org/ccf/1.5/fdb0d1f7-94d5-4628-b3...,2
56,VH_M_central_zone_of_prostate_R,VH_M_peripheral_zone_of_prostate_R,3d-vh-m-prostate,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,2,{http://purl.org/ccf/1.5/66e31648-94e6-4c22-ac...,2
1802,VH_M_cartilage_of_the_tertiary_bronchus_R,VH_M_right_lateral_bronchus,3d-vh-m-lung,{http://purl.org/ccf/1.5/da60f474-614a-4e0a-ad...,{http://purl.org/ccf/1.5/da60f474-614a-4e0a-ad...,1,{http://purl.org/ccf/1.5/da60f474-614a-4e0a-ad...,1
138,VH_F_outer_cortex_of_kidney_L,VH_F_renal_pyramid_L_k,3d-vh-f-kidney-l,{http://purl.org/ccf/1.5/007eb4d9-1694-4380-99...,{http://purl.org/ccf/1.5/fd380a0c-2915-4d73-b3...,1,{http://purl.org/ccf/1.5/fd380a0c-2915-4d73-b3...,1
127,VH_F_outer_cortex_of_kidney_L,VH_F_renal_pyramid_L_a,3d-vh-f-kidney-l,{http://purl.org/ccf/1.5/007eb4d9-1694-4380-99...,{http://purl.org/ccf/1.5/bd004aeb-6e60-4d5b-8d...,1,{http://purl.org/ccf/1.5/bd004aeb-6e60-4d5b-8d...,1
115,VH_F_renal_column_L,VH_F_renal_pyramid_L_k,3d-vh-f-kidney-l,{http://purl.org/ccf/1.5/26edd761-8b50-453c-9b...,{http://purl.org/ccf/1.5/fd380a0c-2915-4d73-b3...,1,{http://purl.org/ccf/1.5/fd380a0c-2915-4d73-b3...,1
604,VH_F_outer_cortex_of_kidney_R,VH_F_renal_pyramid_R_a,3d-vh-f-kidney-r,{http://purl.org/ccf/1.5/2a9e525a-4ad9-4085-bc...,{http://purl.org/ccf/1.5/f66f91f9-c6c5-414d-b7...,1,{http://purl.org/ccf/1.5/1d965182-bf13-4738-af...,1
510,VH_M_kidney_capsule_L,VH_M_outer_cortex_of_kidney_L,3d-vh-m-kidney-l,{http://purl.org/ccf/1.5/f31c1726-c693-4734-8c...,{http://purl.org/ccf/1.5/cf4ba102-edf7-4fe4-bb...,1,{http://purl.org/ccf/1.5/f31c1726-c693-4734-8c...,1
1989,VH_F_left_ventricle,VH_F_right_ventricle,3d-vh-f-heart,{http://purl.org/ccf/1.5/e13cd910-c2df-4b83-ad...,{http://purl.org/ccf/1.5/1fe61622-ba53-47c9-96...,1,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,1
1988,VH_F_interventricular_septum,VH_F_papillary_muscle_of_heart_posmed,3d-vh-f-heart,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,1,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,1
535,VH_M_outer_cortex_of_kidney_L,VH_M_renal_pyramid_L_e,3d-vh-m-kidney-l,{http://purl.org/ccf/1.5/cf4ba102-edf7-4fe4-bb...,{http://purl.org/ccf/1.5/cf4ba102-edf7-4fe4-bb...,1,{http://purl.org/ccf/1.5/cf4ba102-edf7-4fe4-bb...,1
1997,VH_F_interventricular_septum,VH_F_right_ventricle,3d-vh-f-heart,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,{http://purl.org/ccf/1.5/1fe61622-ba53-47c9-96...,1,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,1
1979,VH_F_interventricular_septum,VH_F_left_ventricle,3d-vh-f-heart,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,{http://purl.org/ccf/1.5/e13cd910-c2df-4b83-ad...,1,{http://purl.org/ccf/1.5/05c11830-1526-4472-bd...,1

In [ ]:
total_df_export = total_df[['organ', 'source', 'target', 'sum_extraction_sites_number', 'exact_collisions_with_intersection_space']]

In [ ]:
total_df_export

,organ,source,target,sum_extraction_sites_number,exact_collisions_with_intersection_space
1631,3d-sbu-m-large-intestine,VH_M_rectum,VH_M_sigmoid_colon,6,0
1650,3d-vh-m-small-intestine,VH_M_duodenum_ascending,VH_M_duodenum_horizonal,6,0
159,3d-vh-m-spleen,VH_M_diaphragmatic_surface_of_spleen,VH_M_hilum_of_spleen,4,0
504,3d-vh-m-kidney-l,VH_M_outer_cortex_of_kidney_L,VH_M_renal_pyramid_L_a,3,3
944,3d-vh-f-small-intestine,VH_F_ileum,VH_F_ileum_terminal,3,0
...,...,...,...,...,...
716,3d-vh-m-liver,VH_M_colic_impression_of_liver,VH_M_right_anteroinferior_segment,0,0
715,3d-vh-m-liver,VH_M_left_anterolateral_segment,VH_M_liver_capsule,0,0
714,3d-vh-m-liver,VH_M_colic_impression_of_liver,VH_M_diaphragmatic_surface,0,0
713,3d-vh-m-liver,VH_M_hepataduodenal_ligament,VH_M_ligamentum_venosum,0,0
2000,3d-vh-f-main-bronchus,VH_F_cartilage_of_main_bronchus_L,VH_F_left_main_bronchus,0,0

In [ ]:
total_df_export.to_csv('mesh-pair-intersection-extraction-sites.csv', index=False)