## A comparison of genes between MOSDAP and HRApop/ASCT+B tables

Question: Can I presume, or can you tell me if there are any MOSDAP genes that only appear in one tissue in the other references or in no ASCT+B tables/references?

## Install and import libraries

In [1]:
%pip install requests pandas seaborn

import requests
import pandas as pd
import seaborn as sns
from io import StringIO
from pprint import pprint

Requirement already satisfied: requests in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (2.32.3)
Requirement already satisfied: pandas in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (2.2.3)
Requirement already satisfied: seaborn in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (0.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from requests) (2025.1.31)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.2)
Requirement already satisfied: six>=1.5 in c:\users\abueckle\documents\github\hra-pop-notebooks\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Load data

In [2]:
hra = pd.read_csv('data/MOSDAP HRA Gene Evidence - HRA ASCT+B.csv')
hra['source'] = 'hra'
hra = hra.rename(columns={'gene': 'hgnc'})
hra

,gene_label,ct_label,as_label,as,ct,hgnc,source
0,ABCC9,pericyte,venule,http://purl.obolibrary.org/obo/UBERON_0001979,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra
1,ABCC9,pericyte,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra
2,ABCC9,capillary endothelial cell,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0002144,http://identifiers.org/hgnc/60,hra
3,ACAN,Reparative Chondrocyte,articular cartilage of joint,http://purl.obolibrary.org/obo/UBERON_0010996,https://purl.org/ccf/ASCTB-TEMP_reparative-cho...,http://identifiers.org/hgnc/319,hra
4,ACKR1,blood vessel endothelial cell,venule of lymph node,http://purl.obolibrary.org/obo/UBERON_8410041,http://purl.obolibrary.org/obo/CL_0000071,http://identifiers.org/hgnc/4035,hra
...,...,...,...,...,...,...,...
6629,XCL1,immature NK T cell,medulla of thymus,http://purl.obolibrary.org/obo/UBERON_0002124,http://purl.obolibrary.org/obo/CL_0000914,http://identifiers.org/hgnc/10645,hra
6630,XCL2,natural killer cell,medulla of thymus,http://purl.obolibrary.org/obo/UBERON_0002124,http://purl.obolibrary.org/obo/CL_0000623,http://identifiers.org/hgnc/10646,hra
6631,XCL2,"CD16-negative, CD56-bright natural killer cell...",immune system,http://purl.obolibrary.org/obo/UBERON_0002405,http://purl.obolibrary.org/obo/CL_0000938,http://identifiers.org/hgnc/10646,hra
6632,ZNF683,"CD8-positive, alpha-beta memory T cell",Liver immune resident component,https://purl.org/ccf/ASCTB-TEMP_liver-immune-r...,http://purl.obolibrary.org/obo/CL_0000909,http://identifiers.org/hgnc/28495,hra
6633,ZNF683,CD8aa(II) thymocyte,medulla of thymus,http://purl.obolibrary.org/obo/UBERON_0002124,http://purl.obolibrary.org/obo/CL_0009069,http://identifiers.org/hgnc/28495,hra

In [3]:
hrapop = pd.read_csv('data/MOSDAP HRA Gene Evidence - HRApop Datasets.csv')
hrapop['source'] = 'hrapop'
hrapop = hrapop.rename(columns={'gene': 'hgnc'})
hrapop

,gene_label,ct_label,as_label,avg_mean_gene_expr,cell_instance_count,dataset_count,as,ct,hgnc,source
0,ABCA9,stromal cell,mesenteric lymph node,3.802716,19,1,http://purl.obolibrary.org/obo/UBERON_0002509,http://purl.obolibrary.org/obo/CL_0000499,https://purl.org/ccf/ASCTB-TEMP_abca9,hrapop
1,ABCA9,neuroendocrine cell,lung,3.350485,2,1,http://purl.obolibrary.org/obo/UBERON_0002048,http://purl.obolibrary.org/obo/CL_0000165,http://identifiers.org/hgnc/39,hrapop
2,ABCA9,"CD8-positive, alpha-beta T cell",heart,3.159235,2,1,http://purl.obolibrary.org/obo/UBERON_0000948,http://purl.obolibrary.org/obo/CL_0000625,http://identifiers.org/hgnc/39,hrapop
3,ABCA9,keratocyte,eye,2.957413,2157,7,http://purl.obolibrary.org/obo/UBERON_0000970,http://purl.obolibrary.org/obo/CL_0002363,https://purl.org/ccf/ASCTB-TEMP_abca9,hrapop
4,ABCA9,fibroblast,eye,2.901781,55,4,http://purl.obolibrary.org/obo/UBERON_0000970,http://purl.obolibrary.org/obo/CL_0000057,https://purl.org/ccf/ASCTB-TEMP_abca9,hrapop
...,...,...,...,...,...,...,...,...,...,...
19412,ZNF831,"CD8-positive, alpha-beta T cell",Right posterior basal bronchopulmonary segment,0.311313,1397,2,http://purl.org/sig/ont/fma/fma7362,http://purl.obolibrary.org/obo/CL_0000625,http://identifiers.org/hgnc/16167,hrapop
19413,ZNF831,CD4-positive helper T cell,Right posterior basal bronchopulmonary segment,0.257984,406,1,http://purl.org/sig/ont/fma/fma7362,http://purl.obolibrary.org/obo/CL_0000492,http://identifiers.org/hgnc/16167,hrapop
19414,ZNF831,CD4-positive helper T cell,lung,0.257984,406,1,http://purl.obolibrary.org/obo/UBERON_0002048,http://purl.obolibrary.org/obo/CL_0000492,http://identifiers.org/hgnc/16167,hrapop
19415,ZNF831,"CD8-positive, alpha-beta T cell",lung,0.249502,5513,3,http://purl.obolibrary.org/obo/UBERON_0002048,http://purl.obolibrary.org/obo/CL_0000625,http://identifiers.org/hgnc/16167,hrapop
19416,ZNF831,"CD4-positive, alpha-beta T cell",Medial bronchopulmonary segment,0.019102,12957,1,http://purl.org/sig/ont/fma/fma7360,http://purl.obolibrary.org/obo/CL_0000624,http://identifiers.org/hgnc/16167,hrapop

In [4]:
kpmp = pd.read_csv('data/MOSDAP HRA Gene Evidence - HRA KPMP-HuBMAP (Kidney Only).csv')
kpmp['source'] = 'kpmp'
kpmp = kpmp.rename(columns={'gene': 'hgnc'})
kpmp

,gene_label,ct_label,as_label,avg_mean_gene_expr,as,ct,hgnc,source
0,ACTA2,renal interstitial pericyte,renal papilla,0.963027,http://purl.obolibrary.org/obo/UBERON_0001228,http://purl.obolibrary.org/obo/CL_1001318,http://identifiers.org/hgnc/130,kpmp
1,ACTA2,renal interstitial pericyte,kidney capsule,0.963027,http://purl.obolibrary.org/obo/UBERON_0002015,http://purl.obolibrary.org/obo/CL_1001318,http://identifiers.org/hgnc/130,kpmp
2,ACTA2,renal interstitial pericyte,kidney,0.963027,http://purl.obolibrary.org/obo/UBERON_0002113,http://purl.obolibrary.org/obo/CL_1001318,http://identifiers.org/hgnc/130,kpmp
3,ACTA2,renal interstitial pericyte,kidney blood vessel,0.963027,http://purl.obolibrary.org/obo/UBERON_0003517,http://purl.obolibrary.org/obo/CL_1001318,http://identifiers.org/hgnc/130,kpmp
4,ACTA2,renal interstitial pericyte,kidney pyramid,0.963027,http://purl.obolibrary.org/obo/UBERON_0004200,http://purl.obolibrary.org/obo/CL_1001318,http://identifiers.org/hgnc/130,kpmp
...,...,...,...,...,...,...,...,...
220,VEGFA,podocyte,kidney,2.070876,http://purl.obolibrary.org/obo/UBERON_0002113,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp
221,VEGFA,podocyte,kidney pyramid,2.070876,http://purl.obolibrary.org/obo/UBERON_0004200,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp
222,VEGFA,podocyte,renal column,2.070876,http://purl.obolibrary.org/obo/UBERON_0001284,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp
223,VEGFA,podocyte,outer cortex of kidney,2.070876,http://purl.obolibrary.org/obo/UBERON_0002189,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp
224,VEGFA,podocyte,glomerular visceral epithelium,2.070876,http://purl.obolibrary.org/obo/UBERON_0005751,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp

In [5]:
mosdap = pd.read_csv('data/MOSDAP ST Gene Lists.xlsx - MOSDAP_480_list.csv')
mosdap = mosdap.rename(
  columns={
    'Gene':'gene_label'
  }
)
mosdap

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment
0,BAX,ENSG00000087088,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN
1,BID,ENSG00000015475,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN
2,CASP3,ENSG00000164305,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN
3,CASP8,ENSG00000064012,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN
4,CASP9,ENSG00000132906,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
475,PLN,ENSG00000198523,"stromal, smooth muscle",smooth muscle cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN
476,RBFOX3,ENSG00000167281,"stromal, smooth muscle",smooth muscle,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN
477,SLC24A2,ENSG00000155886,"stromal, smooth muscle",smooth muscle,Tissue expert added,Fallopian Tube,NaN,NaN,False,NaN,False,NaN
478,FOXC2,ENSG00000176692,"stromal, transition","epithelial-mesenchymal transition, embryonic m...",State Rescue; MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN
479,MYH10,ENSG00000133026,"stromal, vascular smooth muscle",vascular smooth muscle,Tissue expert added,HRT,NaN,NaN,False,NaN,False,NaN

In [6]:
url = 'https://apps.humanatlas.io/api/grlc/hra/ensembl-lookup.csv'

# Get the response
response = requests.get(url)
response.raise_for_status()  # will raise an error if request fails

# Wrap response text in StringIO so pandas can read it like a file
json_data = StringIO(response.text)

# Load into DataFrame
look_up = pd.read_csv(json_data)
look_up = look_up.rename(columns={'gene_name': 'gene_label'})
look_up

              ensemble gene_label        hgnc
0      ENSG00000000003     TSPAN6  HGNC:11858
1      ENSG00000000005       TNMD  HGNC:17757
2      ENSG00000000419       DPM1   HGNC:3005
3      ENSG00000000457      SCYL3  HGNC:19285
4      ENSG00000000460      FIRRM  HGNC:25565
...                ...        ...         ...
41201  ENSG00000293312   HNRNPKP3  HGNC:42376
41202  ENSG00000293326  LINC00359  HGNC:42679
41203  ENSG00000293386    LRRC78P  HGNC:54091
41204  ENSG00000293543    DUSP13A  HGNC:56772
41205  ENSG00000293596    SCREEM1  HGNC:56860

[41206 rows x 3 columns]

## Preprocess

### HRA (add organ IRIs)

In [7]:
df_combined = pd.concat([hra, hrapop, kpmp])
df_combined

,gene_label,ct_label,as_label,as,ct,hgnc,source,avg_mean_gene_expr,cell_instance_count,dataset_count
0,ABCC9,pericyte,venule,http://purl.obolibrary.org/obo/UBERON_0001979,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN
1,ABCC9,pericyte,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN
2,ABCC9,capillary endothelial cell,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0002144,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN
3,ACAN,Reparative Chondrocyte,articular cartilage of joint,http://purl.obolibrary.org/obo/UBERON_0010996,https://purl.org/ccf/ASCTB-TEMP_reparative-cho...,http://identifiers.org/hgnc/319,hra,NaN,NaN,NaN
4,ACKR1,blood vessel endothelial cell,venule of lymph node,http://purl.obolibrary.org/obo/UBERON_8410041,http://purl.obolibrary.org/obo/CL_0000071,http://identifiers.org/hgnc/4035,hra,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
220,VEGFA,podocyte,kidney,http://purl.obolibrary.org/obo/UBERON_0002113,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
221,VEGFA,podocyte,kidney pyramid,http://purl.obolibrary.org/obo/UBERON_0004200,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
222,VEGFA,podocyte,renal column,http://purl.obolibrary.org/obo/UBERON_0001284,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
223,VEGFA,podocyte,outer cortex of kidney,http://purl.obolibrary.org/obo/UBERON_0002189,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
224,VEGFA,podocyte,glomerular visceral epithelium,http://purl.obolibrary.org/obo/UBERON_0005751,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN

In [8]:
# add ref-organ
url = 'https://apps.humanatlas.io/api/v1/reference-organs'

# Get the response
response = requests.get(url)
response.raise_for_status()  # will raise an error if request fails

json_data = response.json()
ref_organs = json_data

uberon_ids = set([organ['representation_of']for organ in ref_organs])

In [9]:
# make look-up between as_id and ref_organ
def get_list_as(organ_id:str):
  """Gets a list of all AS in the provided organ

  Args:
      organ_id (str): Organ ID
  """
  url = f'https://apps.humanatlas.io/api/grlc/hra/as-parts?location='+organ_id
  
  headers = {
    'accept':'text/csv'
  }
  
    # Get the response
  response = requests.get(url, headers=headers)
  response.raise_for_status()  # will raise an error if request fails

  # Wrap response text in StringIO so pandas can read it like a file
  csv_data = StringIO(response.text)

  # Load into DataFrame
  df = pd.read_csv(csv_data)
  return df

In [10]:
df_organ_to_as = pd.DataFrame(columns=['organ_iri', 'part_iri', 'part_label'])

for organ_id in uberon_ids:
    as_list = get_list_as(organ_id)

    # add the organ_id as a new column so we can merge cleanly
    as_list = as_list.rename(
        columns={"as_id": "part_iri", "ref_organ": "part_label"})
    as_list["organ_iri"] = organ_id

    # append all rows at once
    df_organ_to_as = pd.concat([df_organ_to_as, as_list], ignore_index=True)
    
df_organ_to_as = df_organ_to_as.rename(columns={'part_iri': 'as'})
df_organ_to_as

,organ_iri,as,part_label
0,http://purl.obolibrary.org/obo/UBERON_0001264,http://purl.obolibrary.org/obo/UBERON_0000006,islet of Langerhans
1,http://purl.obolibrary.org/obo/UBERON_0001264,http://purl.obolibrary.org/obo/UBERON_0000016,endocrine pancreas
2,http://purl.obolibrary.org/obo/UBERON_0001264,http://purl.obolibrary.org/obo/UBERON_0000017,exocrine pancreas
3,http://purl.obolibrary.org/obo/UBERON_0001264,http://purl.obolibrary.org/obo/UBERON_0000482,basal lamina of epithelium
4,http://purl.obolibrary.org/obo/UBERON_0001264,http://purl.obolibrary.org/obo/UBERON_0001064,ventral pancreatic duct
...,...,...,...
5456,http://purl.obolibrary.org/obo/UBERON_0002240,http://purl.obolibrary.org/obo/UBERON_0031906,lumbar spinal cord lateral horn
5457,http://purl.obolibrary.org/obo/UBERON_0002240,http://purl.obolibrary.org/obo/UBERON_0032748,sacral spinal cord ventral horn
5458,http://purl.obolibrary.org/obo/UBERON_0002240,http://purl.obolibrary.org/obo/UBERON_0033483,lumbar spinal cord gray commissure
5459,http://purl.obolibrary.org/obo/UBERON_0002240,http://purl.obolibrary.org/obo/UBERON_0033939,sacral spinal cord dorsal horn
5460,http://purl.obolibrary.org/obo/UBERON_0002118,http://purl.obolibrary.org/obo/UBERON_0002118,right ovary

In [11]:
df_combined_with_organ = pd.merge(df_combined, df_organ_to_as, on='as', how='inner')
df_combined_with_organ

,gene_label,ct_label,as_label,as,ct,hgnc,source,avg_mean_gene_expr,cell_instance_count,dataset_count,organ_iri,part_label
0,ABCC9,pericyte,venule,http://purl.obolibrary.org/obo/UBERON_0001979,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0000079,venule
1,ABCC9,pericyte,venule,http://purl.obolibrary.org/obo/UBERON_0001979,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0004537,venule
2,ABCC9,pericyte,venule,http://purl.obolibrary.org/obo/UBERON_0001979,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0000948,venule
3,ABCC9,pericyte,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0000079,capillary
4,ABCC9,pericyte,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0004537,capillary
...,...,...,...,...,...,...,...,...,...,...,...,...
29692,ZNF831,CD4-positive helper T cell,lung,http://purl.obolibrary.org/obo/UBERON_0002048,http://purl.obolibrary.org/obo/CL_0000492,http://identifiers.org/hgnc/16167,hrapop,0.257984,406.0,1.0,http://purl.obolibrary.org/obo/UBERON_0001004,lung
29693,ZNF831,"CD8-positive, alpha-beta T cell",lung,http://purl.obolibrary.org/obo/UBERON_0002048,http://purl.obolibrary.org/obo/CL_0000625,http://identifiers.org/hgnc/16167,hrapop,0.249502,5513.0,3.0,http://purl.obolibrary.org/obo/UBERON_0001004,lung
29694,PECAM1,endothelial cell,endothelium,http://purl.obolibrary.org/obo/UBERON_0001986,http://purl.obolibrary.org/obo/CL_0000115,http://identifiers.org/hgnc/8823,kpmp,1.741475,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0000079,endothelium
29695,PECAM1,endothelial cell,endothelium,http://purl.obolibrary.org/obo/UBERON_0001986,http://purl.obolibrary.org/obo/CL_0000115,http://identifiers.org/hgnc/8823,kpmp,1.741475,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0004537,endothelium
29696,PECAM1,endothelial cell,endothelium,http://purl.obolibrary.org/obo/UBERON_0001986,http://purl.obolibrary.org/obo/CL_0000115,http://identifiers.org/hgnc/8823,kpmp,1.741475,NaN,NaN,http://purl.obolibrary.org/obo/UBERON_0000948,endothelium

### MOSDAP (add HGNC IDs)

In [12]:
df_mosdap = pd.merge(mosdap, look_up, on='gene_label',
                     how='left').drop(columns=['ensemble'])
df_mosdap

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment,hgnc
0,BAX,ENSG00000087088,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:959
1,BID,ENSG00000015475,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1050
2,CASP3,ENSG00000164305,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1504
3,CASP8,ENSG00000064012,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1509
4,CASP9,ENSG00000132906,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1511
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,PLN,ENSG00000198523,"stromal, smooth muscle",smooth muscle cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:9080
476,RBFOX3,ENSG00000167281,"stromal, smooth muscle",smooth muscle,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:27097
477,SLC24A2,ENSG00000155886,"stromal, smooth muscle",smooth muscle,Tissue expert added,Fallopian Tube,NaN,NaN,False,NaN,False,NaN,HGNC:10976
478,FOXC2,ENSG00000176692,"stromal, transition","epithelial-mesenchymal transition, embryonic m...",State Rescue; MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:3801
479,MYH10,ENSG00000133026,"stromal, vascular smooth muscle",vascular smooth muscle,Tissue expert added,HRT,NaN,NaN,False,NaN,False,NaN,HGNC:7568

## Analyze

In [13]:
# mosdap genes that appear in no ASCT+B tables
no_asctb = df_mosdap[~df_mosdap['gene_label'].isin(df_combined_with_organ.loc[df_combined_with_organ['source'] == 'asctb', 'gene_label'])]
no_asctb

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment,hgnc
0,BAX,ENSG00000087088,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:959
1,BID,ENSG00000015475,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1050
2,CASP3,ENSG00000164305,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1504
3,CASP8,ENSG00000064012,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1509
4,CASP9,ENSG00000132906,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1511
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,PLN,ENSG00000198523,"stromal, smooth muscle",smooth muscle cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:9080
476,RBFOX3,ENSG00000167281,"stromal, smooth muscle",smooth muscle,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:27097
477,SLC24A2,ENSG00000155886,"stromal, smooth muscle",smooth muscle,Tissue expert added,Fallopian Tube,NaN,NaN,False,NaN,False,NaN,HGNC:10976
478,FOXC2,ENSG00000176692,"stromal, transition","epithelial-mesenchymal transition, embryonic m...",State Rescue; MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:3801
479,MYH10,ENSG00000133026,"stromal, vascular smooth muscle",vascular smooth muscle,Tissue expert added,HRT,NaN,NaN,False,NaN,False,NaN,HGNC:7568

In [14]:
# not in hra-pop
not_in_hrapop = df_mosdap[~df_mosdap['gene_label'].isin(
    df_combined_with_organ.loc[df_combined_with_organ['source'] == 'hrapop', 'gene_label'])]
not_in_hrapop

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment,hgnc
45,LINC02360,ENSG00000248300,"endothelial, vascular",vascular endothelium,Tissue expert added,Ovary,NaN,NaN,False,NaN,False,NaN,HGNC:53282
79,KRT71,ENSG00000139648,epithelial,Inner root sheath,Tissue expert added,Skin,NaN,NaN,False,NaN,False,NaN,HGNC:28927
82,LOR,ENSG00000203782,epithelial,epithelial,Tissue expert added,Skin,NaN,NaN,False,NaN,False,NaN,NaN
85,MMP3,ENSG00000149968,epithelial,"epithelial, periosteum, osteocytes/blasts, lun...",Tissue expert added,IVD,NaN,NaN,False,NaN,False,NaN,HGNC:7173
89,PAX1,ENSG00000125813,epithelial,"ventral vertebral column, few thymic stromal",Tissue expert added,IVD,NaN,NaN,False,NaN,False,NaN,HGNC:8615
105,SLC5A8,ENSG00000256870,epithelial,glandular epithelium,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:19119
113,TRIM50,ENSG00000146755,epithelial,paneth cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:19017
125,ZNF750,ENSG00000141579,epithelial,absorptive cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:25843
149,TRIM63,ENSG00000158022,"epithelial, melanocyte",melanocyte,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:16007
318,SLC6A12,ENSG00000111181,"immune, myeloid",Langerhans cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:11045
320,SMIM25,ENSG00000224397,"immune, myeloid",non classical monocyte,Tissue expert added,NaN,PELATON,NaN,False,NaN,False,NaN,NaN
330,NCR2,ENSG00000096264,"immune, NK",activated NK cells,MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:6732
343,MMP13,ENSG00000137745,multiple,"chondrocytes, epithelial, neuronal, cancer",Tissue expert added,IVD,NaN,NaN,False,NaN,False,NaN,HGNC:7159
350,HPGD,ENSG00000164120,multiple? capillary endothelial,"Treg (esp in fat?), lung capillary, other",MxIF Proteins,NaN,NaN,15-PGDH,False,NaN,False,NaN,NaN
355,NRSN1,ENSG00000152954,neural,"ganglion cell,motor neuron",TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:17881
357,PHOX2A,ENSG00000165462,neural,"ganglion cell,motor neuron,sensory neuron",TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:691
364,STMN4,ENSG00000015592,neural,"ganglion cell,motor neuron,sensory neuron",TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:16078
366,TLX2,ENSG00000115297,neural,sensory neuron,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:5057
459,WSCD2,ENSG00000075035,"stromal, skeletal muscle",skeletal muscle cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:29117

In [15]:
# not in kpmp
not_in_kpmp = df_mosdap[~df_mosdap['gene_label'].isin(
    df_combined_with_organ.loc[df_combined_with_organ['source'] == 'kpmp', 'gene_label'])]
not_in_kpmp

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment,hgnc
0,BAX,ENSG00000087088,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:959
1,BID,ENSG00000015475,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1050
2,CASP3,ENSG00000164305,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1504
3,CASP8,ENSG00000064012,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1509
4,CASP9,ENSG00000132906,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1511
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,PLN,ENSG00000198523,"stromal, smooth muscle",smooth muscle cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:9080
476,RBFOX3,ENSG00000167281,"stromal, smooth muscle",smooth muscle,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:27097
477,SLC24A2,ENSG00000155886,"stromal, smooth muscle",smooth muscle,Tissue expert added,Fallopian Tube,NaN,NaN,False,NaN,False,NaN,HGNC:10976
478,FOXC2,ENSG00000176692,"stromal, transition","epithelial-mesenchymal transition, embryonic m...",State Rescue; MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:3801
479,MYH10,ENSG00000133026,"stromal, vascular smooth muscle",vascular smooth muscle,Tissue expert added,HRT,NaN,NaN,False,NaN,False,NaN,HGNC:7568

In [16]:
# Count distinct as_label per gene_label in df_combined
counts = (
    df_combined_with_organ.groupby("gene_label")["organ_iri"]
    .nunique()                      # number of unique as_label per gene_label
    .reset_index(name="organ_count")
)

# Get the list of unique organs per gene_label
organ_lists = (
    df_combined_with_organ.groupby("gene_label")["organ_iri"]
    .unique()  # returns a numpy array of unique organ_iri per gene_label
    .reset_index(name="organ_list")
)

# Merge with your counts if needed
counts_with_list = counts.merge(organ_lists, on="gene_label", how="left")
counts_with_list

    gene_label  organ_count                                         organ_list
0        ABCA9            7  [http://purl.obolibrary.org/obo/UBERON_0000079...
1        ABCC9            6  [http://purl.obolibrary.org/obo/UBERON_0000079...
2         ACAN            1    [http://purl.obolibrary.org/obo/UBERON_0001004]
3        ACER1            1    [http://purl.obolibrary.org/obo/UBERON_0002097]
4        ACKR1           12  [http://purl.obolibrary.org/obo/UBERON_0000079...
..         ...          ...                                                ...
458    ZNF385B            3  [http://purl.obolibrary.org/obo/UBERON_0001004...
459    ZNF385C            2  [http://purl.obolibrary.org/obo/UBERON_0001270...
460     ZNF683            4  [http://purl.obolibrary.org/obo/UBERON_0002107...
461    ZNF804A            5  [http://purl.obolibrary.org/obo/UBERON_0000948...
462     ZNF831            8  [http://purl.obolibrary.org/obo/UBERON_0001270...

[463 rows x 3 columns]

In [17]:
# Merge back onto df_mosdap by matching gene_name to gene_label
df_with_counts = df_mosdap.merge(
    counts_with_list, left_on="gene_label", right_on="gene_label", how="left")

# Fill NaN (if a gene_name never appears)
df_with_counts["organ_count"] = df_with_counts["organ_count"].fillna(0).astype(int)
df_with_counts

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment,hgnc,organ_count,organ_list
0,BAX,ENSG00000087088,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:959,3,[http://purl.obolibrary.org/obo/UBERON_0001004...
1,BID,ENSG00000015475,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1050,7,[http://purl.obolibrary.org/obo/UBERON_0000059...
2,CASP3,ENSG00000164305,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1504,4,[http://purl.obolibrary.org/obo/UBERON_0001004...
3,CASP8,ENSG00000064012,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1509,5,[http://purl.obolibrary.org/obo/UBERON_0000948...
4,CASP9,ENSG00000132906,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:1511,2,[http://purl.obolibrary.org/obo/UBERON_0001270...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,PLN,ENSG00000198523,"stromal, smooth muscle",smooth muscle cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:9080,10,[http://purl.obolibrary.org/obo/UBERON_0001004...
476,RBFOX3,ENSG00000167281,"stromal, smooth muscle",smooth muscle,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:27097,2,[http://purl.obolibrary.org/obo/UBERON_0001255...
477,SLC24A2,ENSG00000155886,"stromal, smooth muscle",smooth muscle,Tissue expert added,Fallopian Tube,NaN,NaN,False,NaN,False,NaN,HGNC:10976,2,[http://purl.obolibrary.org/obo/UBERON_0000955...
478,FOXC2,ENSG00000176692,"stromal, transition","epithelial-mesenchymal transition, embryonic m...",State Rescue; MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:3801,4,[http://purl.obolibrary.org/obo/UBERON_0002370...
479,MYH10,ENSG00000133026,"stromal, vascular smooth muscle",vascular smooth muscle,Tissue expert added,HRT,NaN,NaN,False,NaN,False,NaN,HGNC:7568,6,[http://purl.obolibrary.org/obo/UBERON_0000079...

In [18]:
only_one = df_with_counts[df_with_counts['organ_count'] == 1]
only_one

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,is_in_Xenium_KIL_panel,10x_panel_designer_comment,hgnc,organ_count,organ_list
6,ARX,ENSG00000004848,endocrine,alpha cell,Tissue expert added,pancreas,NaN,NaN,False,NaN,False,NaN,HGNC:18060,1,[http://purl.obolibrary.org/obo/UBERON_0001264]
8,IAPP,ENSG00000121351,endocrine,beta cell,Tissue expert added,pancreas,NaN,NaN,False,NaN,False,NaN,HGNC:5329,1,[http://purl.obolibrary.org/obo/UBERON_0001264]
28,ART4,ENSG00000111339,"endothelial, lymphatic",Lymphatic Endothelium,Tissue expert added,Ovary,NaN,NaN,False,NaN,False,NaN,HGNC:726,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
39,TSPEAR,ENSG00000175894,"endothelial, lymphatic",Lymphatic Endothelium,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:1268,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
40,CADM3-AS1,ENSG00000225670,"endothelial, vascular",vascular endothelium,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:40812,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
51,ADCYAP1R1,ENSG00000078549,epithelial,glandular epithelium,Tissue expert added,Ovary,NaN,NaN,False,NaN,False,NaN,HGNC:242,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
53,AMY2A,ENSG00000243480,epithelial,acinar cell,Tissue expert added,pancreas,NaN,NaN,True,Pancreas - Exocrine glandular cells,False,NaN,HGNC:477,1,[http://purl.obolibrary.org/obo/UBERON_0001264]
55,ARHGAP40,ENSG00000124143,epithelial,absorptive cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:16226,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
63,CXCL6,ENSG00000124875,epithelial,club cell,TOP 5 (CZI) List,NaN,NaN,CXCL4,True,"General - Fibroblasts,Liver - Cholangiocytes,L...",False,NaN,HGNC:10643,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
73,HNF1B,ENSG00000275410,epithelial,glandular epithelium,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:11630,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
75,KCNC3,ENSG00000131398,epithelial,glandular epithelium,Tissue expert added,Ovary,NaN,NaN,False,NaN,False,NaN,HGNC:6235,1,[http://purl.obolibrary.org/obo/UBERON_0001270]
95,SCGB3A2,ENSG00000164265,epithelial,"submocosal glands, bronchiolar epithelium, ? o...",MxIF Proteins,NaN,NaN,NaN,False,NaN,True,NaN,HGNC:18391,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
100,SLC15A1,ENSG00000088386,epithelial,paneth cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:10920,1,[http://purl.obolibrary.org/obo/UBERON_0000059]
101,SLC1A1,ENSG00000106688,epithelial,type I pneumocyte,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:10939,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
102,SLC22A31,ENSG00000259803,epithelial,type II pneumocyte,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:27091,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
106,SLCO1A2,ENSG00000084453,epithelial,tuft cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:10956,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
111,TNS4,ENSG00000131746,epithelial,myoepithelial cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:24352,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
128,DCD,ENSG00000161634,"epithelial, eccrine cells",Eccrine secretory cells,Tissue expert added,Skin,NaN,NaN,False,NaN,False,NaN,HGNC:14669,1,[http://purl.obolibrary.org/obo/UBERON_0002097]
130,DSC1,ENSG00000134765,"epithelial, keratinocytes",Differentiated Keratinocytes,Tissue expert added,Skin,NaN,NaN,False,NaN,False,NaN,HGNC:3035,1,[http://purl.obolibrary.org/obo/UBERON_0002097]
134,KRT2,ENSG00000172867,"epithelial, keratinocytes",Spinous to Granular Cells,Tissue expert added,Skin,NaN,NaN,False,NaN,False,NaN,HGNC:6439,1,[http://purl.obolibrary.org/obo/UBERON_0002097]
147,SIM2,ENSG00000159263,"epithelial, melanocyte",melanocyte,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:10883,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
153,CFAP157,ENSG00000160401,"epithelial, multiciliated",multiciliated cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:27843,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
170,DPPA4,ENSG00000121570,hematopoietic stem cell,hematopoietic stem cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:19200,1,[http://purl.obolibrary.org/obo/UBERON_0001270]
175,ACER1,ENSG00000167769,Immune cells,CD4_RGCC,Tissue expert added,Skin,NaN,NaN,False,NaN,False,NaN,HGNC:18356,1,[http://purl.obolibrary.org/obo/UBERON_0002097]
184,CLEC17A,ENSG00000187912,"immune lymphoid, B",immature B cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:34520,1,[http://purl.obolibrary.org/obo/UBERON_0001270]
257,UGT3A2,ENSG00000168671,"immune lymphoid, thymoctye",double negative thymocyte,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:27266,1,[http://purl.obolibrary.org/obo/UBERON_0002097]
296,KCND3,ENSG00000171385,"immune, myeloid","conventional dendritic cell, cDC1",Tissue expert added,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:6239,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
318,SLC6A12,ENSG00000111181,"immune, myeloid",Langerhans cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:11045,1,[http://purl.obolibrary.org/obo/UBERON_0000955]
354,INA,ENSG00000148798,neural,ganglion cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:6057,1,[http://purl.obolibrary.org/obo/UBERON_0000955]
360,PMP2,ENSG00000147588,neural,schwann cell,TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:9117,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
368,TTC9B,ENSG00000174521,neural,"ganglion cell,sensory neuron",TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:26395,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
381,FOXO4,ENSG00000184481,senescence markers,with TP53 induces senescence,State Rescue; MxIF Proteins,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:7139,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
418,TECRL,ENSG00000205678,"stromal, cardiac muscle","atrial cardiac myocyte,ventricular cardiac myo...",TOP 5 (CZI) List,NaN,NaN,NaN,False,NaN,False,NaN,HGNC:27365,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
424,ACAN,ENSG00000157766,"stromal, chondrocyte","chondrocytes, CNS",Tissue expert added,IVD,NaN,NaN,False,NaN,False,NaN,HGNC:319,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
425,COL10A1,ENSG00000123500,"stromal, chondrocyte",hypertrophic chondrocytes,Tissue expert added,IVD,NaN,NaN,False,NaN,False,NaN,HGNC:2185,1,[http://purl.obolibrary.org/obo/UBERON_0001004]
437,IGSF10,ENSG00000152580,"stromal, fibroblasts",fibroblast,Tissue expert added,Ovary,NaN,NaN,False,NaN,False,NaN,HGNC:26384,1,[http://purl.obolibrary.org/obo/UBERON_0001270]
441,PWWP3B,ENSG00000157502,"stromal, fibroblasts",fibroblast,Tissue expert added,Ovary,NaN,NaN,False,NaN,False,NaN,HGNC:26583,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
443,SHC3,ENSG00000148082,"stromal, fibroblasts",fibroblast,Tissue expert added,Uterus,NaN,NaN,False,NaN,False,NaN,HGNC:18181,1,[http://purl.obolibrary.org/obo/UBERON_0000948]
471,JPH2,ENSG00000149596,"stromal, smooth muscle",smooth muscle,Tissue expert added,Fallopian Tube,NaN,NaN,False,NaN,False,NaN,HGNC:14202,1,[http://purl.obolibrary.org/obo/UBERON_0001004]

## Not in MOSDAP

In [19]:
# load data
not_mosdap_hra_genes = pd.read_csv('data/NOT-mosdap-hra-genes.csv')
not_mosdap_hra_pop_genes = pd.read_csv('data/NOT-mosdap-hra-pop-genes.csv')
not_mosdap_kpmp_hubmap_genes = pd.read_csv('data/NOT-mosdap-kpmp-hubmap-genes.csv')

In [20]:
not_mosdap_hra_genes['source'] = 'hra'
not_mosdap_hra_pop_genes['source'] = 'hrapop'
not_mosdap_kpmp_hubmap_genes['source'] = 'kpmp'

In [21]:
df_not_in_mosdap = pd.concat([not_mosdap_hra_genes, not_mosdap_hra_pop_genes, not_mosdap_kpmp_hubmap_genes])
df_not_in_mosdap = df_not_in_mosdap.rename(columns={'gene': 'hgnc'})
df_not_in_mosdap

,gene_label,hgnc,source
0,A2M,http://identifiers.org/hgnc/7,hra
1,ABC10-43608400O15.1,https://purl.org/ccf/ASCTB-TEMP_abc10-43608400...,hra
2,ABCA1,http://identifiers.org/hgnc/29,hra
3,ABCA13,http://identifiers.org/hgnc/14638,hra
4,ABCA3,http://identifiers.org/hgnc/33,hra
...,...,...,...
281,WSB1,http://identifiers.org/hgnc/19221,kpmp
282,WWOX,http://identifiers.org/hgnc/12799,kpmp
283,ZEB1,http://identifiers.org/hgnc/11642,kpmp
284,ZEB2,http://identifiers.org/hgnc/14881,kpmp
285,ZFPM2,http://identifiers.org/hgnc/16700,kpmp

In [22]:
print(f'Unique genes NOT in MOSDAP: {df_not_in_mosdap['hgnc'].nunique()}')

Unique genes NOT in MOSDAP: 29754

## Unique genes by source

In [23]:
# step 1: drop duplicates on (gene, source)
unique_pairs = df_combined[['gene_label', 'source']
                           ].drop_duplicates(subset=["gene_label", "source"])

# step 2: count per gene
result = (
    unique_pairs.groupby("gene_label")
    .size()
    .reset_index(name="unique_source_count")
)

above_two = result[result['unique_source_count'] > 1]
above_two

    gene_label  unique_source_count
1        ABCC9                    2
2         ACAN                    2
4        ACKR1                    2
5        ACTA2                    3
6        ACTG2                    2
..         ...                  ...
457       WIF1                    2
459        WT1                    2
461       XCL1                    2
462       XCL2                    2
466     ZNF683                    2

[274 rows x 2 columns]

In [24]:
# step 1: drop duplicates on (gene, source)
unique_pairs = df_not_in_mosdap[['gene_label', 'source']
                           ].drop_duplicates(subset=["gene_label", "source"])

# step 2: count per gene
result = (
    unique_pairs.groupby("gene_label")
    .size()
    .reset_index(name="unique_source_count")
)

above_two = result[result['unique_source_count'] > 1]
above_two

      gene_label  unique_source_count
2            A2M                    2
27         ABCA1                    2
30        ABCA13                    2
32         ABCA3                    2
33         ABCA4                    2
...          ...                  ...
21105      ZFHX3                    2
21127      ZFPM2                    2
21128  ZFPM2-AS1                    2
21151       ZIC1                    2
21548  ZNF736P9Y                    2

[1522 rows x 2 columns]

In [25]:
unique_pairs

              gene_label source
0                    A2M    hra
1    ABC10-43608400O15.1    hra
2                  ABCA1    hra
3                 ABCA13    hra
4                  ABCA3    hra
..                   ...    ...
281                 WSB1   kpmp
282                 WWOX   kpmp
283                 ZEB1   kpmp
284                 ZEB2   kpmp
285                ZFPM2   kpmp

[23326 rows x 2 columns]

## Gene by source

In [26]:
# create df with all sources
df_mosdap['source'] = 'mosdap'
df_not_in_mosdap = df_not_in_mosdap.rename(columns={
  'gene_name':'gene_label'
})
df_not_in_mosdap

,gene_label,hgnc,source
0,A2M,http://identifiers.org/hgnc/7,hra
1,ABC10-43608400O15.1,https://purl.org/ccf/ASCTB-TEMP_abc10-43608400...,hra
2,ABCA1,http://identifiers.org/hgnc/29,hra
3,ABCA13,http://identifiers.org/hgnc/14638,hra
4,ABCA3,http://identifiers.org/hgnc/33,hra
...,...,...,...
281,WSB1,http://identifiers.org/hgnc/19221,kpmp
282,WWOX,http://identifiers.org/hgnc/12799,kpmp
283,ZEB1,http://identifiers.org/hgnc/11642,kpmp
284,ZEB2,http://identifiers.org/hgnc/14881,kpmp
285,ZFPM2,http://identifiers.org/hgnc/16700,kpmp

In [27]:
df_combined

,gene_label,ct_label,as_label,as,ct,hgnc,source,avg_mean_gene_expr,cell_instance_count,dataset_count
0,ABCC9,pericyte,venule,http://purl.obolibrary.org/obo/UBERON_0001979,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN
1,ABCC9,pericyte,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0000669,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN
2,ABCC9,capillary endothelial cell,capillary,http://purl.obolibrary.org/obo/UBERON_0001982,http://purl.obolibrary.org/obo/CL_0002144,http://identifiers.org/hgnc/60,hra,NaN,NaN,NaN
3,ACAN,Reparative Chondrocyte,articular cartilage of joint,http://purl.obolibrary.org/obo/UBERON_0010996,https://purl.org/ccf/ASCTB-TEMP_reparative-cho...,http://identifiers.org/hgnc/319,hra,NaN,NaN,NaN
4,ACKR1,blood vessel endothelial cell,venule of lymph node,http://purl.obolibrary.org/obo/UBERON_8410041,http://purl.obolibrary.org/obo/CL_0000071,http://identifiers.org/hgnc/4035,hra,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
220,VEGFA,podocyte,kidney,http://purl.obolibrary.org/obo/UBERON_0002113,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
221,VEGFA,podocyte,kidney pyramid,http://purl.obolibrary.org/obo/UBERON_0004200,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
222,VEGFA,podocyte,renal column,http://purl.obolibrary.org/obo/UBERON_0001284,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
223,VEGFA,podocyte,outer cortex of kidney,http://purl.obolibrary.org/obo/UBERON_0002189,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN
224,VEGFA,podocyte,glomerular visceral epithelium,http://purl.obolibrary.org/obo/UBERON_0005751,http://purl.obolibrary.org/obo/CL_0000653,http://identifiers.org/hgnc/12680,kpmp,2.070876,NaN,NaN

In [28]:
df_all_genes_with_source = pd.concat([df_mosdap, df_not_in_mosdap, df_combined])
df_all_genes_with_source

,gene_label,Ensembl ID,Lineage/ L1 or state,cell type(s),Rationale/Source,Specific Request by,specificity flag,Protein/Other name,is_in_10x_multi_panel,10x_multi_panel_celltype,...,10x_panel_designer_comment,hgnc,source,ct_label,as_label,as,ct,avg_mean_gene_expr,cell_instance_count,dataset_count
0,BAX,ENSG00000087088,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,...,NaN,HGNC:959,mosdap,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BID,ENSG00000015475,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,...,NaN,HGNC:1050,mosdap,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CASP3,ENSG00000164305,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,...,NaN,HGNC:1504,mosdap,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CASP8,ENSG00000064012,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,...,NaN,HGNC:1509,mosdap,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CASP9,ENSG00000132906,apoptosis,multiple,Tissue expert added,NaN,NaN,NaN,False,NaN,...,NaN,HGNC:1511,mosdap,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,VEGFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://identifiers.org/hgnc/12680,kpmp,podocyte,kidney,http://purl.obolibrary.org/obo/UBERON_0002113,http://purl.obolibrary.org/obo/CL_0000653,2.070876,NaN,NaN
221,VEGFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://identifiers.org/hgnc/12680,kpmp,podocyte,kidney pyramid,http://purl.obolibrary.org/obo/UBERON_0004200,http://purl.obolibrary.org/obo/CL_0000653,2.070876,NaN,NaN
222,VEGFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://identifiers.org/hgnc/12680,kpmp,podocyte,renal column,http://purl.obolibrary.org/obo/UBERON_0001284,http://purl.obolibrary.org/obo/CL_0000653,2.070876,NaN,NaN
223,VEGFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://identifiers.org/hgnc/12680,kpmp,podocyte,outer cortex of kidney,http://purl.obolibrary.org/obo/UBERON_0002189,http://purl.obolibrary.org/obo/CL_0000653,2.070876,NaN,NaN
224,VEGFA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,http://identifiers.org/hgnc/12680,kpmp,podocyte,glomerular visceral epithelium,http://purl.obolibrary.org/obo/UBERON_0005751,http://purl.obolibrary.org/obo/CL_0000653,2.070876,NaN,NaN

In [29]:
df_all_genes_with_source['gene_label'].nunique()

22193

In [30]:
df_unique = df_all_genes_with_source[[
    'gene_label', 'source']].drop_duplicates()
df_unique

    gene_label  source
0          BAX  mosdap
1          BID  mosdap
2        CASP3  mosdap
3        CASP8  mosdap
4        CASP9  mosdap
..         ...     ...
197       SPP1    kpmp
198     THEMIS    kpmp
205     TPSAB1    kpmp
212      TPSB2    kpmp
219      VEGFA    kpmp

[24581 rows x 2 columns]

In [31]:
# assuming df has columns: gene_label, source
df_wide = (
    df_unique.assign(val=1)  # add helper column
    .pivot_table(index="gene_label",
                 columns="source",
                 values="val",
                 aggfunc="max",
                 fill_value=0)
    .reset_index()
)

# optionally rename columns to match your desired style
df_wide = df_wide.rename(columns={
    'mosdap': 'in_mosdap',
    'hra': 'in_hra',
    'hrapop': 'in_hra_pop',
    'kpmp': 'in_kpmp'
})
df_wide

source,gene_label,in_hra,in_hra_pop,in_kpmp,in_mosdap
0,A1BG,0,1,0,0
1,A1CF,0,1,0,0
2,A2M,1,1,0,0
3,A2M-AS1,0,1,0,0
4,A2MP1,0,1,0,0
...,...,...,...,...,...
22188,substance P (SP),1,0,0,0
22189,synaptophysin,1,0,0,0
22190,tropomyosin,1,0,0,0
22191,truncated/phosphorylated forms of AQP0,1,0,0,0
22192,uroguanylin,1,0,0,0

## Export

In [32]:
no_asctb.to_csv('output/no-asctb.csv', index=False)
not_in_hrapop.to_csv('output/not-in-hra-pop.csv', index=False)
not_in_kpmp.to_csv('output/not-in-kpmp.csv', index=False)
only_one.to_csv('output/only-one-tissue-hra-pop.csv', index=False)
df_mosdap.to_csv('output/mosdap_gene_list_with_hgnc.csv', index=False)
df_not_in_mosdap.to_csv('output/not-in-mosdap.csv', index=False)
df_combined.to_csv('output/genes-hra-resources-combined.csv', index=False)
df_wide.to_csv('output/gene_by_source_wide.csv', index=False)