## Code to query, visualize, and use output from the HRA Workflow Runner downstream

## Install and import libraries

In [8]:
%pip install duckdb pandas requests hra-jupyter-widgets ipywidgets

import duckdb
import json
from pprint import pprint
import requests
import pandas as pd
import ipywidgets as widgets

from shared import ORGAN_MAPPING

Requirement already satisfied: duckdb in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (1.2.2)
Requirement already satisfied: pandas in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: requests in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (2.32.3)
Requirement already satisfied: hra-jupyter-widgets in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (0.4.1)
Requirement already satisfied: ipywidgets in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (8.1.7)
Requirement already satisfied: numpy>=1.22.4 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from requests) (2025.4.26)
Requirement already satisfied: anywidget in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from hra-jupyter-widgets) (0.9.18)
Requirement already satisfied: traitlets>=5.10 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from hra-jupyter-widgets) (5.14.3)
Requirement already satisfied: comm>=0.1.3 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipywidgets) (8.36.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: decorator in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: exceptiongroup in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.2.2)
Requirement already satisfied: jedi>=0.16 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack_data in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.13.2)
Requirement already satisfied: wcwidth in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: psygnal>=0.8.1 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from anywidget->hra-jupyter-widgets) (0.13.0)
Requirement already satisfied: executing>=1.2.0 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [9]:
# import Jupyter widgets
from hra_jupyter_widgets import (
    EuiOrganInformation,
    Eui
)

## Global settings

In [10]:
tool_of_interest = 'azimuth'

# get organ from look-up
organ_of_interest = f'http://purl.obolibrary.org/obo/UBERON_{ORGAN_MAPPING["heart"].split(":")[-1]}'

## Fetch and process cell instances

In [11]:
# Combine cell instances and normalize columns for analysis
data_dir = "data/gtex"
query = f"""
SELECT
  split_part(filename, '/', 3) as dataset,
  Organ_ID as organ,
  split_part(filename, '/', 4) as tool,
  column00 as cell,
  clid as cell_id,
  CL_Label as cell_label,
  match_type,
  COALESCE("mapping.score", conf_score, popv_prediction_score / 6, 0) as confidence_score,
FROM read_csv('{ data_dir }/*/*/annotations.csv', union_by_name = true, filename = true, ignore_errors=true, quote='"')
"""

cells = duckdb.sql(query)
cells.write_csv(f'{ data_dir }/cell-instances.csv.gz')
cells.show()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────────────────────────────┬────────────────┬─────────┬─────────────────────────────────┬────────────┬─────────────────────────────────────┬─────────────────┬────────────────────┐
│            dataset            │     organ      │  tool   │              cell               │  cell_id   │             cell_label              │   match_type    │  confidence_score  │
│            varchar            │    varchar     │ varchar │             varchar             │  varchar   │               varchar               │     varchar     │       double       │
├───────────────────────────────┼────────────────┼─────────┼─────────────────────────────────┼────────────┼─────────────────────────────────────┼─────────────────┼────────────────────┤
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TATGCCCGTTCTGAAC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_AGATTGCCATGGGACA-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                0.5 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TTGACTTGTACACCGC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_CACTCCATCTGGAGCC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │ 0.8333333333333334 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_GTGCTTCAGTGAATTG-prostate │ CL:0000192 │ smooth muscle cell                  │ skos:exactMatch │ 0.8333333333333334 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_CACACAAAGCAAATCA-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_CTGGTCTAGTGCGTGA-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TCGTAGATCACCACCT-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TAGTGGTCATCTCGCT-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TAAGAGAAGACAGACC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │ 0.6666666666666666 │
│               ·               │       ·        │  ·      │              ·                  │     ·      │             ·                       │        ·        │          ·         │
│               ·               │       ·        │  ·      │              ·                  │     ·      │             ·                       │        ·        │          ·         │
│               ·               │       ·        │  ·      │              ·                  │     ·      │             ·                       │        ·        │          ·         │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CTAGAGTTCTGCTTGC-heart    │ CL:1000413 │ endothelial cell of artery          │ skos:exactMatch │  0.892433202610579 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CGCGGTAAGTTCGATC-heart    │ CL:0000623 │ natural killer cell                 │ skos:exactMatch │ 0.7439126027805105 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_ATTGGTGCACAGGCCT-heart    │ CL:0002131 │ regular ventricular cardiac myocyte │ skos:exactMatch │ 0.7464198444613545 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_AACTCAGTCGAATGCT-heart    │ CL:0002573 │ Schwann cell                        │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CAGCAGCTCATACGGT-heart    │ CL:0000623 │ natural killer cell                 │ skos:exactMatch │ 0.9551184274168342 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_TCGCGTTGTCAAAGCG-heart    │ CL:0000235 │ macrophage                          │ skos:exactMatch │ 0.7239919774274294 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_AACTCCCAGAAGGACA-heart    │ CL:1000413 │ endothelial cell of artery          │ skos:exactMatch │ 0.8159056018243378 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CAGAATCGTATAGGGC-heart    │ CL:1000414 │ endothelial cell of venule          │ skos:exactMatch │ 0.8441983392960823 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_AGCGTCGTCCGTTGTC-heart    │ CL:1000414 │ endothelial cell of venule          │ skos:exactMatch │ 0.9293715391424932 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_GCGGGTTCAATGGAGC-heart    │ CL:0000057 │ fibroblast                          │ skos:exactMatch │ 0.8572748811180838 │
├───────────────────────────────┴────────────────┴─────────┴─────────────────────────────────┴────────────┴─────────────────────────────────────┴─────────────────┴────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                              8 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [26]:
df_dvl_llm_4 = cells.to_df()
df_dvl_llm_4

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,dataset,organ,tool,cell,cell_id,cell_label,match_type,confidence_score
0,GTEX-GTEX-12BJ1-5007-SM-H8L6U,UBERON:0002367,popv,CST04_TATGCCCGTTCTGAAC-prostate,CL:0002340,luminal cell of prostate epithelium,skos:exactMatch,1.000000
1,GTEX-GTEX-12BJ1-5007-SM-H8L6U,UBERON:0002367,popv,CST04_AGATTGCCATGGGACA-prostate,CL:0002340,luminal cell of prostate epithelium,skos:exactMatch,0.500000
2,GTEX-GTEX-12BJ1-5007-SM-H8L6U,UBERON:0002367,popv,CST04_TTGACTTGTACACCGC-prostate,CL:0002340,luminal cell of prostate epithelium,skos:exactMatch,1.000000
3,GTEX-GTEX-12BJ1-5007-SM-H8L6U,UBERON:0002367,popv,CST04_CACTCCATCTGGAGCC-prostate,CL:0002340,luminal cell of prostate epithelium,skos:exactMatch,0.833333
4,GTEX-GTEX-12BJ1-5007-SM-H8L6U,UBERON:0002367,popv,CST04_GTGCTTCAGTGAATTG-prostate,CL:0000192,smooth muscle cell,skos:exactMatch,0.833333
...,...,...,...,...,...,...,...,...
331838,GTEX-GTEX-1R9PN-5002-SM-HD2MC,UBERON:0001911,popv,TST01_AGCGTCGGTTGAGTTC-breast,CL:0002326,luminal epithelial cell of mammary gland,skos:exactMatch,1.000000
331839,GTEX-GTEX-1R9PN-5002-SM-HD2MC,UBERON:0001911,popv,TST01_CGGTTAAGTCAAAGAT-breast,CL:0000235,macrophage,skos:exactMatch,0.666667
331840,GTEX-GTEX-1R9PN-5002-SM-HD2MC,UBERON:0001911,popv,TST01_GGGATGAGTACAGTTC-breast,CL:0002326,luminal epithelial cell of mammary gland,skos:exactMatch,0.833333
331841,GTEX-GTEX-1R9PN-5002-SM-HD2MC,UBERON:0001911,popv,TST01_ATAGACCAGTTGAGAT-breast,CL:0002326,luminal epithelial cell of mammary gland,skos:exactMatch,0.833333
331842,GTEX-GTEX-1R9PN-5002-SM-HD2MC,UBERON:0001911,popv,TST01_AGAGTGGTCGGAGGTA-breast,CL:0000236,B cell,skos:exactMatch,0.333333

In [27]:
df_dvl_llm_4.to_csv('output/dvl-llm-4-gtex-cells.csv', index=False)

In [12]:
# Show only cells annotated with a user-specified tool
cells.filter(f"tool = '{tool_of_interest}'")

┌───────────────────────────────┬──────────────────────┬─────────┬─────────────────────────────┬────────────────────┬────────────┬──────────────────────┬────────────────────┐
│            dataset            │        organ         │  tool   │            cell             │      cell_id       │ cell_label │      match_type      │  confidence_score  │
│            varchar            │       varchar        │ varchar │           varchar           │      varchar       │  varchar   │       varchar        │       double       │
├───────────────────────────────┼──────────────────────┼─────────┼─────────────────────────────┼────────────────────┼────────────┼──────────────────────┼────────────────────┤
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_TCTTTCCTCTGCTTGC-lung │ 0.935159738908882  │ None       │ AT2                  │ 1.0000000000000002 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_TCGTACCGTCAGCTAT-lung │ 0.9262700597571508 │ None       │ AT2                  │ 0.9825864029578535 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_ATTATCCAGGCCCGTT-lung │ 0.9345360959522296 │ None       │ AT2                  │ 0.9345360959522296 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_GCGCAGTAGCTACCGC-lung │ 0.9128188406475647 │ None       │ AT2                  │                1.0 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_ATCATCTAGTCACGCC-lung │ 0.9475832161057612 │ None       │ AT2                  │ 0.9999999999999997 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_CACACAACATGAAGTA-lung │ 0.8582850062951333 │ None       │ AT2                  │ 0.8582850062951333 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_GACTACAGTTAAAGTG-lung │ 0.4820470099565222 │ None       │ AT1                  │ 0.4928594965441799 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_CCGGGATCAAACTGCT-lung │ 0.9592909813659262 │ None       │ AT2                  │ 0.9999999999999999 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_TTGACTTTCTTCAACT-lung │ 0.9084187977120182 │ None       │ AT2                  │ 0.9084187977120182 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_CTCAGAATCGTAGGAG-lung │ 0.9544784883254089 │ None       │ AT2                  │                1.0 │
│               ·               │  ·                   │    ·    │              ·              │         ·          │  ·         │  ·                   │                 ·  │
│               ·               │  ·                   │    ·    │              ·              │         ·          │  ·         │  ·                   │                 ·  │
│               ·               │  ·                   │    ·    │              ·              │         ·          │  ·         │  ·                   │                 ·  │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_CTCACACTCGAATGCT-lung │ 0.9279843328253786 │ None       │ AT2                  │ 0.9279843328253786 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ Alveolar macrophages │ azimuth │ TST03_AAAGTAGGTCTAGTGT-lung │ 0.5181625504339988 │ None       │ Alveolar macrophages │   0.96494704058258 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_TGTCCCATCGTATCAG-lung │ 0.8509238872255773 │ None       │ AT1                  │ 0.8509238872255773 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_GATGAGGGTCCGACGT-lung │ 0.8193687307731168 │ None       │ AT2                  │ 0.8404955616725349 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_CCTATTATCGGCGGTT-lung │ 1.0000000000000002 │ None       │ AT1                  │ 1.0000000000000002 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_ATCATCTTCGGGAGTA-lung │ 0.7865978902490603 │ None       │ AT2                  │ 0.7865978902490603 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ Alveolar macrophages │ azimuth │ TST03_TATCTCAGTTCGCGAC-lung │ 0.5550881118758979 │ None       │ Alveolar macrophages │ 0.9208195915864432 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_GGCCGATAGGATCGCA-lung │ 0.9999999999999998 │ None       │ AT1                  │ 0.9999999999999998 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_TGTCCCAAGAATTCCC-lung │ 1.0                │ None       │ AT1                  │                1.0 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_CATCGGGTCGCCTGAG-lung │ 1.0000000000000002 │ None       │ AT2                  │ 1.0000000000000002 │
├───────────────────────────────┴──────────────────────┴─────────┴─────────────────────────────┴────────────────────┴────────────┴──────────────────────┴────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                    8 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [14]:

# Cell summary of all cells (counted 3x because run with 3 annotation tools)
cells.aggregate("cell_id, first(cell_label) as cell_label, count(cell) as cell_count").order("cell_count DESC")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────────────────────────────────────────┬───────────────────────────────────────────────────────────┬────────────┐
│                  cell_id                  │                        cell_label                         │ cell_count │
│                  varchar                  │                          varchar                          │   int64    │
├───────────────────────────────────────────┼───────────────────────────────────────────────────────────┼────────────┤
│ CL:0002063                                │ type II pneumocyte                                        │      43255 │
│ CL:0002131                                │ regular ventricular cardiac myocyte                       │      26119 │
│ CL:0000057                                │ fibroblast                                                │      23106 │
│ CL:0002062                                │ type I pneumocyte                                         │      21931 │
│ CL:0000235                                │ macrophage                                                │      20086 │
│ CL:0000192                                │ smooth muscle cell                                        │      10980 │
│ CL:0002326                                │ luminal epithelial cell of mammary gland                  │      10893 │
│ CL:0002153                                │ corneocyte                                                │      10262 │
│ CL:0002548                                │ fibroblast of cardiac tissue                              │       9726 │
│ CL:0000746                                │ cardiac muscle cell                                       │       9543 │
│     ·                                     │          ·                                                │          · │
│     ·                                     │          ·                                                │          · │
│     ·                                     │          ·                                                │          · │
│ CL:0000792                                │ CD4-positive, CD25-positive, alpha-beta regulatory T cell │          3 │
│ ASCTB-TEMP:alveolar-m-proliferating       │ Alveolar Mφ proliferating                                 │          3 │
│ CL:0002068                                │ Purkinje myocyte                                          │          2 │
│ CL:0001058                                │ plasmacytoid dendritic cell, human                        │          2 │
│ ASCTB-TEMP:cd8-positive-alpha-beta-t-cell │ CD8-positive, alpha-beta T cell                           │          2 │
│ ASCTB-TEMP:pneumocyte                     │ pneumocyte                                                │          1 │
│ CL:0000546                                │ T-helper 2 cell                                           │          1 │
│ ASCTB-TEMP:conventional-dendritic-cell    │ conventional dendritic cell                               │          1 │
│ CL:0000038                                │ erythroid progenitor cell                                 │          1 │
│ CL:0002072                                │ nodal myocyte                                             │          1 │
├───────────────────────────────────────────┴───────────────────────────────────────────────────────────┴────────────┤
│ 138 rows (20 shown)                                                                                      3 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [15]:
# Cell summaries by tool
summaries = cells.aggregate("tool, cell_id, first(cell_label) as cell_label, count(cell) as cell_count").order("tool, cell_count DESC")
df = summaries.to_df()
df

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,tool,cell_id,cell_label,cell_count
0,azimuth,CL:0002131,regular ventricular cardiac myocyte,17242
1,azimuth,CL:0002063,type II pneumocyte,14179
2,azimuth,CL:0000057,fibroblast,10803
3,azimuth,CL:0002062,type I pneumocyte,8780
4,azimuth,CL:4028002,alveolar capillary type 1 endothelial cell,3906
...,...,...,...,...
205,popv,ASCTB-TEMP:pneumocyte,pneumocyte,1
206,popv,CL:0000038,erythroid progenitor cell,1
207,popv,CL:0017000,pulmonary ionocyte,1
208,popv,CL:0002394,CD141-positive myeloid dendritic cell,1
209,popv,ASCTB-TEMP:conventional-dendritic-cell,conventional dendritic cell,1

## Transform `df` for downstream usage in HRA US#2 UI

In [16]:
# transform df to fit requirements for HRA US#2 at https://apps.humanatlas.io/us2
df['percentage'] = df['cell_count'].apply(lambda c: c/df['cell_count'].sum())

# add column for modality
df['modality'] = 'sc_transcriptomics'

# rename columns as needed
df = df.rename(columns=
  {
    'cell_count':'count'
  }
)

# new column order
new_order = ['tool', 'modality', 'percentage', 'count', 'cell_label','cell_id']

# reassign columns
df_renamed = df[new_order]

df_renamed

,tool,modality,percentage,count,cell_label,cell_id
0,azimuth,sc_transcriptomics,0.051958,17242,regular ventricular cardiac myocyte,CL:0002131
1,azimuth,sc_transcriptomics,0.042728,14179,type II pneumocyte,CL:0002063
2,azimuth,sc_transcriptomics,0.032555,10803,fibroblast,CL:0000057
3,azimuth,sc_transcriptomics,0.026458,8780,type I pneumocyte,CL:0002062
4,azimuth,sc_transcriptomics,0.011771,3906,alveolar capillary type 1 endothelial cell,CL:4028002
...,...,...,...,...,...,...
205,popv,sc_transcriptomics,0.000003,1,pneumocyte,ASCTB-TEMP:pneumocyte
206,popv,sc_transcriptomics,0.000003,1,erythroid progenitor cell,CL:0000038
207,popv,sc_transcriptomics,0.000003,1,pulmonary ionocyte,CL:0017000
208,popv,sc_transcriptomics,0.000003,1,CD141-positive myeloid dendritic cell,CL:0002394
209,popv,sc_transcriptomics,0.000003,1,conventional dendritic cell,ASCTB-TEMP:conventional-dendritic-cell

In [17]:
# Export to CSV
df_renamed.to_csv('output/cell_summary.csv', index=False)

## Transform `df` for call to HRA API

In [18]:
# Use HRA API to get predictions: https://apps.humanatlas.io/api/#post-/hra-pop/cell-summary-report
# Convert to CSV string (no index, line breaks handled)
csv_string = df_renamed.to_csv(index=False, lineterminator='\n')

# set URL
url = 'https://apps.humanatlas.io/api/hra-pop/cell-summary-report'

# set headers for the request
headers = {
    'accept': 'application/json',
    'content-type': 'application/json'
}

# set body
body = {
  "csvString": csv_string,
  "organ": organ_of_interest,
  "tool": tool_of_interest
}

# make call and capture response
response = requests.post(url, headers=headers, data=json.dumps(body))

# Check the response
if response.status_code == 200:
    data_dict  = response.json()
    print("Request was successful!")
else:
    print(f"Error: {response.status_code}")

Request was successful!

## Inspect HRA API reponse

In [19]:
# capture response as df, sort to show AS first, then datasets, then extraction sites, and then highest similarity within each
df_response = pd.DataFrame(data_dict ['sources']).sort_values(by=['cell_source_type','similarity'], ascending=[True, False])
df_response

,cell_source,cell_source_type,cell_source_label,cell_source_link,tool,modality,similarity
100,http://purl.org/sig/ont/fma/fma7267,http://purl.org/ccf/AnatomicalStructure,Posteromedial head of posterior papillary musc...,None,azimuth,None,0.266957
107,http://purl.obolibrary.org/obo/UBERON_0002094,http://purl.org/ccf/AnatomicalStructure,interventricular septum,None,azimuth,None,0.264219
112,http://purl.obolibrary.org/obo/UBERON_0002080,http://purl.org/ccf/AnatomicalStructure,heart right ventricle,None,azimuth,None,0.260661
189,http://purl.obolibrary.org/obo/UBERON_0002079,http://purl.org/ccf/AnatomicalStructure,left cardiac atrium,None,azimuth,None,0.184380
206,http://purl.obolibrary.org/obo/UBERON_0002084,http://purl.org/ccf/AnatomicalStructure,heart left ventricle,None,azimuth,None,0.139877
...,...,...,...,...,...,...,...
660,http://purl.org/ccf/1.5/57bab703-98bd-4106-916...,http://purl.org/ccf/SpatialEntity,None,None,azimuth,None,0.012228
687,http://purl.org/ccf/1.5/63b2f5a9-5914-4c45-923...,http://purl.org/ccf/SpatialEntity,None,None,azimuth,None,0.005766
700,http://purl.org/ccf/1.5/502f175c-9d55-4341-b6f...,http://purl.org/ccf/SpatialEntity,None,None,azimuth,None,0.002069
703,http://purl.org/ccf/1.5/6f055461-adb2-41fe-86c...,http://purl.org/ccf/SpatialEntity,None,None,azimuth,None,0.001500
704,http://purl.org/ccf/1.5/7f7fe1b0-d9f6-48c2-a30...,http://purl.org/ccf/SpatialEntity,None,None,azimuth,None,0.000533

## Visualize extraction sites with EUI

In [20]:
pprint(data_dict['rui_locations'])

{'@context': 'https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld',
 '@graph': [{'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032_Donor',
             '@type': 'Donor',
             'age': '3',
             'consortium_name': 'NHLBI/LungMap',
             'description': 'Entered 3/24/2023, Allen Wang, NHLBI/LungMap',
             'label': 'Male, Age 3',
             'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
             'provider_name': 'NHLBI/LungMap',
             'provider_uuid': '0ec3cf4a-4a28-496a-b66e-df34f4cd32e1',
             'samples': {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032_Donor_TissueBlock1',
                         '@type': 'Sample',
                         'datasets': [{'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D122$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D150$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D175$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'}],
                         'description': '5 x 5 x 3 millimeter, 3 millimeter',
                         'donor': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032_Donor',
                         'label': 'Registered 3/24/2023, Allen Wang, '
                                  'NHLBI/LungMap',
                         'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                         'rui_location': {'@id': 'ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0',
                                          '@type': 'SpatialEntity',
                                          'ccf_annotations': ['http://purl.obolibrary.org/obo/UBERON_0002048',
                                                              '../sig/ont/fma/fma7360',
                                                              '../sig/ont/fma/fma7361',
                                                              '../sig/ont/fma/fma7363',
                                                              '../sig/ont/fma/fma7401'],
                                          'creation_date': '2023-04-25',
                                          'creator': 'Allen Wang',
                                          'creator_first_name': 'Allen',
                                          'creator_last_name': 'Wang',
                                          'dimension_units': 'millimeter',
                                          'placement': {'@id': 'ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0_placement',
                                                        '@type': 'SpatialPlacement',
                                                        'creation_date': '2023-04-25',
                                                        'rotation_order': 'XYZ',
                                                        'rotation_units': 'degree',
                                                        'scaling_units': 'ratio',
                                                        'source': 'ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0',
                                                        'target': 'ccf:latest/ccf.owl#VHMLung',
                                                        'translation_units': 'millimeter',
                                                        'x_rotation': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                       '@value': '-101'},
                                                        'x_scaling': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                      '@value': '1'},
                                                        'x_translation': {'@type': 'http://www.w3.org/2001/XMLSchema#double',
                                                                          '@value': '49.919'},
                                                        'y_rotation': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                       '@value': '134'},
                                                        'y_scaling': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                      '@value': '1'},
                                                        'y_translation': {'@type': 'http://www.w3.org/2001/XMLSchema#double',
                                                                          '@value': '101.788'},
                                                        'z_rotation': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                       '@value': '77'},
                                                        'z_scaling': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                      '@value': '1'},
                                                        'z_translation': {'@type': 'http://www.w3.org/2001/XMLSchema#double',
                                                                          '@value': '110.357'}},
                                          'x_dimension': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                          '@value': '5'},
                                          'y_dimension': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                          '@value': '5'},
                                          'z_dimension': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                          '@value': '3'}},
                         'sample_type': 'Tissue Block',
                         'sections': None},
             'sex': 'Male'},
            {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046_Donor',
             '@type': 'Donor',
             'age': '3',
             'consortium_name': 'NHLBI/LungMap',
             'description': 'Entered 3/24/2023, Allen Wang, NHLBI/LungMap',
             'label': 'Male, Age 3',
             'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
             'provider_name': 'NHLBI/LungMap',
             'provider_uuid': '0ec3cf4a-4a28-496a-b66e-df34f4cd32e1',
             'samples': {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046_Donor_TissueBlock1',
                         '@type': 'Sample',
                         'datasets': [{'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D122$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D150$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'},
                                      {'@id': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D175$lung',
                                       '@type': 'Dataset',
                                       'description': 'Data/Assay Types: '
                                                      'OTHER, ',
                                       'label': 'Registered 3/24/2023, Allen '
                                                'Wang, NHLBI/LungMap',
                                       'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                                       'technology': 'OTHER',
                                       'thumbnail': 'assets/logo.jpg'}],
                         'description': '5 x 5 x 3 millimeter, 3 millimeter',
                         'donor': 'https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046_Donor',
                         'label': 'Registered 3/24/2023, Allen Wang, '
                                  'NHLBI/LungMap',
                         'link': 'https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76',
                         'rui_location': {'@id': 'ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0',
                                          '@type': 'SpatialEntity',
                                          'ccf_annotations': ['http://purl.obolibrary.org/obo/UBERON_0002048',
                                                              '../sig/ont/fma/fma7360',
                                                              '../sig/ont/fma/fma7361',
                                                              '../sig/ont/fma/fma7363',
                                                              '../sig/ont/fma/fma7401'],
                                          'creation_date': '2023-04-25',
                                          'creator': 'Allen Wang',
                                          'creator_first_name': 'Allen',
                                          'creator_last_name': 'Wang',
                                          'dimension_units': 'millimeter',
                                          'placement': {'@id': 'ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0_placement',
                                                        '@type': 'SpatialPlacement',
                                                        'creation_date': '2023-04-25',
                                                        'rotation_order': 'XYZ',
                                                        'rotation_units': 'degree',
                                                        'scaling_units': 'ratio',
                                                        'source': 'ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0',
                                                        'target': 'ccf:latest/ccf.owl#VHMLung',
                                                        'translation_units': 'millimeter',
                                                        'x_rotation': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                       '@value': '-101'},
                                                        'x_scaling': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                      '@value': '1'},
                                                        'x_translation': {'@type': 'http://www.w3.org/2001/XMLSchema#double',
                                                                          '@value': '49.919'},
                                                        'y_rotation': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                       '@value': '134'},
                                                        'y_scaling': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                      '@value': '1'},
                                                        'y_translation': {'@type': 'http://www.w3.org/2001/XMLSchema#double',
                                                                          '@value': '101.788'},
                                                        'z_rotation': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                       '@value': '77'},
                                                        'z_scaling': {'@type': 'http://www.w3.org/2001/XMLSchema#integer',
                                                                      '@value': '1'},
                                                        'z_translation': {'@type': 'http://www.w3.org/2001/XMLSchema#double',

In [21]:
# Step 1: Convert the dict to a JSON string
inline_jsonld_str = json.dumps(data_dict['rui_locations'], indent=0)

In [22]:
# Step 2: Wrap it in a list and convert to JSON string again
data_sources_attr = [inline_jsonld_str]

In [23]:
pprint(data_sources_attr)

['{\n'
 '"@context": '
 '"https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",\n'
 '"@graph": [\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032_Donor",\n'
 '"samples": {\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032_Donor_TissueBlock1",\n'
 '"@type": "Sample",\n'
 '"donor": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032_Donor",\n'
 '"datasets": [\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D122$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D150$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D175$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '}\n'
 '],\n'
 '"rui_location": {\n'
 '"@id": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0",\n'
 '"placement": {\n'
 '"@id": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0_placement",\n'
 '"@type": "SpatialPlacement",\n'
 '"source": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0",\n'
 '"target": "ccf:latest/ccf.owl#VHMLung",\n'
 '"rotation_order": "XYZ",\n'
 '"rotation_units": "degree",\n'
 '"scaling_units": "ratio",\n'
 '"translation_units": "millimeter",\n'
 '"x_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "-101"\n'
 '},\n'
 '"x_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"x_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "49.919"\n'
 '},\n'
 '"y_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "134"\n'
 '},\n'
 '"y_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"y_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "101.788"\n'
 '},\n'
 '"z_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "77"\n'
 '},\n'
 '"z_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"z_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "110.357"\n'
 '},\n'
 '"creation_date": "2023-04-25"\n'
 '},\n'
 '"@type": "SpatialEntity",\n'
 '"ccf_annotations": [\n'
 '"http://purl.obolibrary.org/obo/UBERON_0002048",\n'
 '"../sig/ont/fma/fma7360",\n'
 '"../sig/ont/fma/fma7361",\n'
 '"../sig/ont/fma/fma7363",\n'
 '"../sig/ont/fma/fma7401"\n'
 '],\n'
 '"creator_first_name": "Allen",\n'
 '"creator_last_name": "Wang",\n'
 '"dimension_units": "millimeter",\n'
 '"x_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "5"\n'
 '},\n'
 '"y_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "5"\n'
 '},\n'
 '"z_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "3"\n'
 '},\n'
 '"creation_date": "2023-04-25",\n'
 '"creator": "Allen Wang"\n'
 '},\n'
 '"sample_type": "Tissue Block",\n'
 '"sections": null,\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "5 x 5 x 3 millimeter, 3 millimeter",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '"@type": "Donor",\n'
 '"age": "3",\n'
 '"consortium_name": "NHLBI/LungMap",\n'
 '"sex": "Male",\n'
 '"provider_name": "NHLBI/LungMap",\n'
 '"provider_uuid": "0ec3cf4a-4a28-496a-b66e-df34f4cd32e1",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Entered 3/24/2023, Allen Wang, NHLBI/LungMap",\n'
 '"label": "Male, Age 3"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046_Donor",\n'
 '"samples": {\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046_Donor_TissueBlock1",\n'
 '"@type": "Sample",\n'
 '"donor": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046_Donor",\n'
 '"datasets": [\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D122$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D150$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D175$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '}\n'
 '],\n'
 '"rui_location": {\n'
 '"@id": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0",\n'
 '"placement": {\n'
 '"@id": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0_placement",\n'
 '"@type": "SpatialPlacement",\n'
 '"source": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0",\n'
 '"target": "ccf:latest/ccf.owl#VHMLung",\n'
 '"rotation_order": "XYZ",\n'
 '"rotation_units": "degree",\n'
 '"scaling_units": "ratio",\n'
 '"translation_units": "millimeter",\n'
 '"x_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "-101"\n'
 '},\n'
 '"x_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"x_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "49.919"\n'
 '},\n'
 '"y_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "134"\n'
 '},\n'
 '"y_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"y_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "101.788"\n'
 '},\n'
 '"z_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "77"\n'
 '},\n'
 '"z_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"z_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "110.357"\n'
 '},\n'
 '"creation_date": "2023-04-25"\n'
 '},\n'
 '"@type": "SpatialEntity",\n'
 '"ccf_annotations": [\n'
 '"http://purl.obolibrary.org/obo/UBERON_0002048",\n'
 '"../sig/ont/fma/fma7360",\n'
 '"../sig/ont/fma/fma7361",\n'
 '"../sig/ont/fma/fma7363",\n'
 '"../sig/ont/fma/fma7401"\n'
 '],\n'
 '"creator_first_name": "Allen",\n'
 '"creator_last_name": "Wang",\n'
 '"dimension_units": "millimeter",\n'
 '"x_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "5"\n'
 '},\n'
 '"y_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "5"\n'
 '},\n'
 '"z_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "3"\n'
 '},\n'
 '"creation_date": "2023-04-25",\n'
 '"creator": "Allen Wang"\n'
 '},\n'
 '"sample_type": "Tissue Block",\n'
 '"sections": null,\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "5 x 5 x 3 millimeter, 3 millimeter",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '"@type": "Donor",\n'
 '"age": "3",\n'
 '"consortium_name": "NHLBI/LungMap",\n'
 '"sex": "Male",\n'
 '"provider_name": "NHLBI/LungMap",\n'
 '"provider_uuid": "0ec3cf4a-4a28-496a-b66e-df34f4cd32e1",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Entered 3/24/2023, Allen Wang, NHLBI/LungMap",\n'
 '"label": "Male, Age 3"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062_Donor",\n'
 '"samples": {\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062_Donor_TissueBlock1",\n'
 '"@type": "Sample",\n'
 '"donor": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062_Donor",\n'
 '"datasets": [\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D062$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D032$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D046$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D122$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D150$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D175$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '}\n'
 '],\n'
 '"rui_location": {\n'
 '"@id": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0",\n'
 '"placement": {\n'
 '"@id": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0_placement",\n'
 '"@type": "SpatialPlacement",\n'
 '"source": "ccf:1.5/da60f474-614a-4e0a-adbe-521ba44c7bf0",\n'
 '"target": "ccf:latest/ccf.owl#VHMLung",\n'
 '"rotation_order": "XYZ",\n'
 '"rotation_units": "degree",\n'
 '"scaling_units": "ratio",\n'
 '"translation_units": "millimeter",\n'
 '"x_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "-101"\n'
 '},\n'
 '"x_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"x_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "49.919"\n'
 '},\n'
 '"y_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "134"\n'
 '},\n'
 '"y_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"y_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "101.788"\n'
 '},\n'
 '"z_rotation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "77"\n'
 '},\n'
 '"z_scaling": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "1"\n'
 '},\n'
 '"z_translation": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#double",\n'
 '"@value": "110.357"\n'
 '},\n'
 '"creation_date": "2023-04-25"\n'
 '},\n'
 '"@type": "SpatialEntity",\n'
 '"ccf_annotations": [\n'
 '"http://purl.obolibrary.org/obo/UBERON_0002048",\n'
 '"../sig/ont/fma/fma7360",\n'
 '"../sig/ont/fma/fma7361",\n'
 '"../sig/ont/fma/fma7363",\n'
 '"../sig/ont/fma/fma7401"\n'
 '],\n'
 '"creator_first_name": "Allen",\n'
 '"creator_last_name": "Wang",\n'
 '"dimension_units": "millimeter",\n'
 '"x_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "5"\n'
 '},\n'
 '"y_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "5"\n'
 '},\n'
 '"z_dimension": {\n'
 '"@type": "http://www.w3.org/2001/XMLSchema#integer",\n'
 '"@value": "3"\n'
 '},\n'
 '"creation_date": "2023-04-25",\n'
 '"creator": "Allen Wang"\n'
 '},\n'
 '"sample_type": "Tissue Block",\n'
 '"sections": null,\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "5 x 5 x 3 millimeter, 3 millimeter",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '"@type": "Donor",\n'
 '"consortium_name": "NHLBI/LungMap",\n'
 '"sex": "Male",\n'
 '"provider_name": "NHLBI/LungMap",\n'
 '"provider_uuid": "0ec3cf4a-4a28-496a-b66e-df34f4cd32e1",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Entered 3/24/2023, Allen Wang, NHLBI/LungMap",\n'
 '"label": "Male"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D088_Donor",\n'
 '"samples": {\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D088_Donor_TissueBlock1",\n'
 '"@type": "Sample",\n'
 '"donor": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D088_Donor",\n'
 '"datasets": [\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D088$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D231$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'
 '"label": "Registered 3/24/2023, Allen Wang, NHLBI/LungMap"\n'
 '},\n'
 '{\n'
 '"@id": '
 '"https://api.cellxgene.cziscience.com/dp/v1/collections/625f6bf4-2f33-4942-962e-35243d284837#D139$lung",\n'
 '"@type": "Dataset",\n'
 '"technology": "OTHER",\n'
 '"thumbnail": "assets/logo.jpg",\n'
 '"link": '
 '"https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76",\n'
 '"description": "Data/Assay Types: OTHER, ",\n'

In [24]:
# Convert to JSON-LD string
jsonld_str = json.dumps(data_dict ['rui_locations'], indent=2)

eui_component = Eui(selected_organs = [organ_of_interest], 
                                    data_sources = data_sources_attr
                                    # data_sources = ['https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/v0.12.0/output-data/v0.12.0/atlas-dataset-graph.jsonld']
                                    )
display(eui_component)

Eui(data_sources=['{\n"@context": "https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",\n"@gra…

In [25]:
target = requests.get('https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/v0.12.0/output-data/v0.12.0/atlas-dataset-graph.jsonld')
pprint(target.text)

('{\n'
 ' "@context": {\n'
 '  "CL": {\n'
 '   "@id": "http://purl.obolibrary.org/obo/CL_",\n'
 '   "@prefix": true\n'
 '  },\n'
 '  "ASCTB-TEMP": {\n'
 '   "@id": "https://purl.org/ccf/ASCTB-TEMP_",\n'
 '   "@prefix": true\n'
 '  },\n'
 '  "ctpop": {\n'
 '   "@id": "https://purl.humanatlas.io/graph/hra-pop#",\n'
 '   "@prefix": true\n'
 '  },\n'
 '  "as_3d_id": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "as_id": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "all_collisions": {\n'
 '   "@id": "ccf:has_collision_summary"\n'
 '  },\n'
 '  "collision_source": {\n'
 '   "@reverse": "ccf:has_collision_summary",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "collisions": {\n'
 '   "@id": "ccf:has_collision_item"\n'
 '  },\n'
 '  "corridor_source": {\n'
 '   "@reverse": "ccf:has_corridor",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "corridor": {\n'
 '   "@id": "ccf:has_corridor"\n'
 '  },\n'
 '  "aggregated_cell_source": {\n'
 '   "@id": "ccf:cell_source",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "summaries": {\n'
 '   "@id": "ccf:has_cell_summary"\n'
 '  },\n'
 '  "cell_source": {\n'
 '   "@reverse": "ccf:has_cell_summary",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "aggregated_summaries": {\n'
 '   "@id": "ccf:aggregates"\n'
 '  },\n'
 '  "annotation_method": {\n'
 '   "@id": "ccf:cell_annotation_method"\n'
 '  },\n'
 '  "summary": {\n'
 '   "@id": "ccf:has_cell_summary_row"\n'
 '  },\n'
 '  "cell_id": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "count": {\n'
 '   "@id": "ccf:cell_count"\n'
 '  },\n'
 '  "percentage": {\n'
 '   "@id": "ccf:percentage_of_total"\n'
 '  },\n'
 '  "cell_count": {\n'
 '   "@id": "ccf:cell_count",\n'
 '   "@type": "xsd:integer"\n'
 '  },\n'
 '  "gene_count": {\n'
 '   "@id": "ccf:gene_count",\n'
 '   "@type": "xsd:integer"\n'
 '  },\n'
 '  "organ_id": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "cell_source_a": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "cell_source_b": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "entity_a": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "entity_b": {\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "@base": "http://purl.org/ccf/",\n'
 '  "@vocab": "http://purl.org/ccf/",\n'
 '  "ccf": "http://purl.org/ccf/",\n'
 '  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",\n'
 '  "dcterms": "http://purl.org/dc/terms/",\n'
 '  "label": "rdfs:label",\n'
 '  "description": "rdfs:comment",\n'
 '  "link": "ccf:url",\n'
 '  "sex": "ccf:sex",\n'
 '  "age": "ccf:age",\n'
 '  "bmi": "ccf:bmi",\n'
 '  "consortium_name": "ccf:consortium_name",\n'
 '  "provider_name": "ccf:tissue_provider_name",\n'
 '  "provider_uuid": "ccf:tissue_provider_uuid",\n'
 '  "donor": {\n'
 '   "@id": "ccf:comes_from",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "samples": {\n'
 '   "@reverse": "donor"\n'
 '  },\n'
 '  "sections": {\n'
 '   "@id": "ccf:subdivided_into_sections",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "datasets": {\n'
 '   "@id": "ccf:generates_dataset",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "sample_type": "ccf:sample_type",\n'
 '  "section_count": "ccf:section_count",\n'
 '  "section_size": "ccf:section_size",\n'
 '  "section_units": "ccf:section_size_unit",\n'
 '  "section_number": "ccf:section_number",\n'
 '  "rui_location": {\n'
 '   "@id": "ccf:has_registration_location",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "ccf_annotations": {\n'
 '   "@id": "ccf:collides_with",\n'
 '   "@type": "@id",\n'
 '   "@container": "@set"\n'
 '  },\n'
 '  "representation_of": {\n'
 '   "@id": "ccf:representation_of",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "reference_organ": {\n'
 '   "@id": "ccf:has_reference_organ",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "extraction_set_for": {\n'
 '   "@id": "ccf:extraction_set_for",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "extraction_set": {\n'
 '   "@id": "ccf:has_extraction_set",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "organ_owner_sex": "ccf:organ_owner_sex",\n'
 '  "side": "ccf:organ_side",\n'
 '  "rui_rank": "ccf:rui_rank",\n'
 '  "slice_thickness": "ccf:slice_thickness",\n'
 '  "slice_count": "ccf:slice_count",\n'
 '  "object": {\n'
 '   "@id": "ccf:has_object_reference",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "creation_date": "dcterms:created",\n'
 '  "updated_date": "ccf:updated_date",\n'
 '  "creator": "dcterms:creator",\n'
 '  "creator_first_name": "ccf:creator_first_name",\n'
 '  "creator_last_name": "ccf:creator_last_name",\n'
 '  "placement": {\n'
 '   "@reverse": "ccf:placement_for"\n'
 '  },\n'
 '  "placement_date": "dcterms:created",\n'
 '  "rotation_order": "ccf:rotation_order",\n'
 '  "dimension_units": "ccf:dimension_unit",\n'
 '  "rotation_units": "ccf:rotation_unit",\n'
 '  "scaling_units": "ccf:scaling_unit",\n'
 '  "translation_units": "ccf:translation_unit",\n'
 '  "source": {\n'
 '   "@id": "ccf:placement_for",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "target": {\n'
 '   "@id": "ccf:placement_relative_to",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "x_rotation": "ccf:x_rotation",\n'
 '  "y_rotation": "ccf:y_rotation",\n'
 '  "z_rotation": "ccf:z_rotation",\n'
 '  "x_scaling": "ccf:x_scaling",\n'
 '  "y_scaling": "ccf:y_scaling",\n'
 '  "z_scaling": "ccf:z_scaling",\n'
 '  "x_translation": "ccf:x_translation",\n'
 '  "y_translation": "ccf:y_translation",\n'
 '  "z_translation": "ccf:z_translation",\n'
 '  "x_dimension": "ccf:x_dimension",\n'
 '  "y_dimension": "ccf:y_dimension",\n'
 '  "z_dimension": "ccf:z_dimension",\n'
 '  "ontology_terms": {\n'
 '   "@id": "ccf:has_ontology_term",\n'
 '   "@type": "@id"\n'
 '  },\n'
 '  "technology": "ccf:technology",\n'
 '  "thumbnail": "ccf:thumbnail",\n'
 '  "file": "ccf:file_url",\n'
 '  "file_format": "ccf:file_format",\n'
 '  "file_subpath": "ccf:file_subpath"\n'
 ' },\n'
 ' "@graph": [\n'
 '  {\n'
 '   "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/1628b6f7eb615862322d6274a6bc9fa0",\n'
 '   "@type": "Donor",\n'
 '   "samples": [\n'
 '    {\n'
 '     "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/0b43d8d0dbbc5e3923a8b963650ab8e3",\n'
 '     "@type": "Sample",\n'
 '     "datasets": [],\n'
 '     "sections": [\n'
 '      {\n'
 '       "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/35e16f13caab262f446836f63cf4ad42",\n'
 '       "@type": "Sample",\n'
 '       "datasets": [\n'
 '        {\n'
 '         "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/3de525fe3e5718f297e8d62e037a042d",\n'
 '         "@type": "Dataset",\n'
 '         "link": '
 '"https://portal.hubmapconsortium.org/browse/dataset/3de525fe3e5718f297e8d62e037a042d",\n'
 '         "technology": "RNAseq",\n'
 '         "cell_count": "6000",\n'
 '         "gene_count": "60286",\n'
 '         "organ_id": "http://purl.obolibrary.org/obo/UBERON_0002108",\n'
 '         "label": "Registered 11/3/2023, HuBMAP Process, TMC-Stanford",\n'
 '         "description": "Dataset Type: RNAseq [Salmon]",\n'
 '         "thumbnail": "assets/icons/ico-unknown.svg"\n'
 '        }\n'
 '       ],\n'
 '       "sample_type": "Tissue Section",\n'
 '       "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/35e16f13caab262f446836f63cf4ad42",\n'
 '       "label": "Registered 2/16/2022, daniel Cotter, TMC-Stanford",\n'
 '       "description": "3 x 30 x 7.5 millimeter, 7.5 millimeter"\n'
 '      }\n'
 '     ],\n'
 '     "sample_type": "Tissue Block",\n'
 '     "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/0b43d8d0dbbc5e3923a8b963650ab8e3",\n'
 '     "label": "Registered 2/16/2022, amir Bahmani, TMC-Stanford",\n'
 '     "description": "3 x 30 x 15 millimeter, 7.5 millimeter, 2 Sections",\n'
 '     "rui_location": {\n'
 '      "@context": '
 '"https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",\n'
 '      "@id": '
 '"http://purl.org/ccf/1.5/e240c0a4-5e53-4464-8320-ad775f2c4bf7",\n'
 '      "@type": "SpatialEntity",\n'
 '      "ccf_annotations": [\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0002115",\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0002116"\n'
 '      ],\n'
 '      "creation_date": "2022-02-16",\n'
 '      "creator": "Yiing Lin",\n'
 '      "creator_first_name": "Yiing",\n'
 '      "creator_last_name": "Lin",\n'
 '      "dimension_units": "millimeter",\n'
 '      "placement": {\n'
 '       "@context": '
 '"https://hubmapconsortium.github.io/hubmap-ontology/ccf-context.jsonld",\n'
 '       "@id": '
 '"http://purl.org/ccf/1.5/e240c0a4-5e53-4464-8320-ad775f2c4bf7_placement",\n'
 '       "@type": "SpatialPlacement",\n'
 '       "placement_date": "2022-02-16",\n'
 '       "rotation_order": "XYZ",\n'
 '       "rotation_units": "degree",\n'
 '       "scaling_units": "ratio",\n'
 '       "target": "http://purl.org/ccf/latest/ccf.owl#VHFSmallIntestine",\n'
 '       "translation_units": "millimeter",\n'
 '       "x_rotation": 0,\n'
 '       "x_scaling": 1,\n'
 '       "x_translation": 130.806,\n'
 '       "y_rotation": 0,\n'
 '       "y_scaling": 1,\n'
 '       "y_translation": 111.09,\n'
 '       "z_rotation": 86,\n'
 '       "z_scaling": 1,\n'
 '       "z_translation": 54.023\n'
 '      },\n'
 '      "x_dimension": 3,\n'
 '      "y_dimension": 30,\n'
 '      "z_dimension": 15\n'
 '     }\n'
 '    },\n'
 '    {\n'
 '     "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/3838f4672dd3d3d1ee6cb0809cf1ea03",\n'
 '     "@type": "Sample",\n'
 '     "datasets": [],\n'
 '     "sections": [\n'
 '      {\n'
 '       "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/3d742332ef8ca26f34f7ee5b9da3381c",\n'
 '       "@type": "Sample",\n'
 '       "datasets": [\n'
 '        {\n'
 '         "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/7edbff53248f2a2c8e74f5f955681734",\n'
 '         "@type": "Dataset",\n'
 '         "link": '
 '"https://portal.hubmapconsortium.org/browse/dataset/7edbff53248f2a2c8e74f5f955681734",\n'
 '         "technology": "RNAseq",\n'
 '         "cell_count": "5995",\n'
 '         "gene_count": "60286",\n'
 '         "organ_id": "http://purl.obolibrary.org/obo/UBERON_0000059",\n'
 '         "label": "Registered 11/3/2023, HuBMAP Process, TMC-Stanford",\n'
 '         "description": "Dataset Type: RNAseq [Salmon]",\n'
 '         "thumbnail": "assets/icons/ico-unknown.svg"\n'
 '        }\n'
 '       ],\n'
 '       "sample_type": "Tissue Section",\n'
 '       "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/3d742332ef8ca26f34f7ee5b9da3381c",\n'
 '       "label": "Registered 2/16/2022, daniel Cotter, TMC-Stanford",\n'
 '       "description": "20 x 50 x 1 millimeter, 1 millimeter"\n'
 '      }\n'
 '     ],\n'
 '     "sample_type": "Tissue Block",\n'
 '     "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/3838f4672dd3d3d1ee6cb0809cf1ea03",\n'
 '     "label": "Registered 10/19/2021, amir Bahmani, TMC-Stanford",\n'
 '     "description": "20 x 50 x 5 millimeter, 1 millimeter, 1 Sections",\n'
 '     "rui_location": {\n'
 '      "@context": '
 '"https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",\n'
 '      "@id": '
 '"http://purl.org/ccf/1.5/f9e28182-3ed3-4a3f-bd45-66ebce1efafb",\n'
 '      "@type": "SpatialEntity",\n'
 '      "ccf_annotations": [\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0001156",\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0001157",\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0001159",\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0001158",\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0022276"\n'
 '      ],\n'
 '      "creation_date": "2021-10-19",\n'
 '      "creator": "Yiing Lin",\n'
 '      "creator_first_name": "Yiing",\n'
 '      "creator_last_name": "Lin",\n'
 '      "dimension_units": "millimeter",\n'
 '      "placement": {\n'
 '       "@context": '
 '"https://hubmapconsortium.github.io/hubmap-ontology/ccf-context.jsonld",\n'
 '       "@id": '
 '"http://purl.org/ccf/1.5/f9e28182-3ed3-4a3f-bd45-66ebce1efafb_placement",\n'
 '       "@type": "SpatialPlacement",\n'
 '       "placement_date": "2021-10-19",\n'
 '       "rotation_order": "XYZ",\n'
 '       "rotation_units": "degree",\n'
 '       "scaling_units": "ratio",\n'
 '       "target": "http://purl.org/ccf/latest/ccf.owl#VHFColon",\n'
 '       "translation_units": "millimeter",\n'
 '       "x_rotation": 0,\n'
 '       "x_scaling": 1,\n'
 '       "x_translation": 245.289,\n'
 '       "y_rotation": 90,\n'
 '       "y_scaling": 1,\n'
 '       "y_translation": 147.807,\n'
 '       "z_rotation": 0,\n'
 '       "z_scaling": 1,\n'
 '       "z_translation": 109.874\n'
 '      },\n'
 '      "slice_count": 1,\n'
 '      "slice_thickness": 1,\n'
 '      "x_dimension": 20,\n'
 '      "y_dimension": 50,\n'
 '      "z_dimension": 5\n'
 '     }\n'
 '    },\n'
 '    {\n'
 '     "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/507bb20f36adc8a513fe31a913bcfde6",\n'
 '     "@type": "Sample",\n'
 '     "datasets": [],\n'
 '     "sections": [\n'
 '      {\n'
 '       "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/8332815c55f72e2aec5610dcb4eab9d7",\n'
 '       "@type": "Sample",\n'
 '       "datasets": [\n'
 '        {\n'
 '         "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/11678046b4e78f95762acc47d3074dc5",\n'
 '         "@type": "Dataset",\n'
 '         "link": '
 '"https://portal.hubmapconsortium.org/browse/dataset/11678046b4e78f95762acc47d3074dc5",\n'
 '         "technology": "RNAseq",\n'
 '         "cell_count": "6000",\n'
 '         "gene_count": "60286",\n'
 '         "organ_id": "http://purl.obolibrary.org/obo/UBERON_0002108",\n'
 '         "label": "Registered 11/3/2023, HuBMAP Process, TMC-Stanford",\n'
 '         "description": "Dataset Type: RNAseq [Salmon]",\n'
 '         "thumbnail": "assets/icons/ico-unknown.svg"\n'
 '        }\n'
 '       ],\n'
 '       "sample_type": "Tissue Section",\n'
 '       "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/8332815c55f72e2aec5610dcb4eab9d7",\n'
 '       "label": "Registered 2/16/2022, daniel Cotter, TMC-Stanford",\n'
 '       "description": "3 x 30 x 5 millimeter, 5 millimeter"\n'
 '      }\n'
 '     ],\n'
 '     "sample_type": "Tissue Block",\n'
 '     "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/507bb20f36adc8a513fe31a913bcfde6",\n'
 '     "label": "Registered 2/16/2022, amir Bahmani, TMC-Stanford",\n'
 '     "description": "3 x 30 x 15 millimeter, 5 millimeter, 3 Sections",\n'
 '     "rui_location": {\n'
 '      "@context": '
 '"https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",\n'
 '      "@id": '
 '"http://purl.org/ccf/1.5/65f3b03b-1eb1-487d-8c02-c4d107cc9400",\n'
 '      "@type": "SpatialEntity",\n'
 '      "ccf_annotations": [\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0002114",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14926",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14928"\n'
 '      ],\n'
 '      "creation_date": "2022-02-16",\n'
 '      "creator": "Yiing Lin",\n'
 '      "creator_first_name": "Yiing",\n'
 '      "creator_last_name": "Lin",\n'
 '      "dimension_units": "millimeter",\n'
 '      "placement": {\n'
 '       "@context": '
 '"https://hubmapconsortium.github.io/hubmap-ontology/ccf-context.jsonld",\n'
 '       "@id": '
 '"http://purl.org/ccf/1.5/65f3b03b-1eb1-487d-8c02-c4d107cc9400_placement",\n'
 '       "@type": "SpatialPlacement",\n'
 '       "placement_date": "2022-02-16",\n'
 '       "rotation_order": "XYZ",\n'
 '       "rotation_units": "degree",\n'
 '       "scaling_units": "ratio",\n'
 '       "target": "http://purl.org/ccf/latest/ccf.owl#VHFSmallIntestine",\n'
 '       "translation_units": "millimeter",\n'
 '       "x_rotation": 0,\n'
 '       "x_scaling": 1,\n'
 '       "x_translation": 33.438,\n'
 '       "y_rotation": 0,\n'
 '       "y_scaling": 1,\n'
 '       "y_translation": 196.307,\n'
 '       "z_rotation": -37,\n'
 '       "z_scaling": 1,\n'
 '       "z_translation": 15.419\n'
 '      },\n'
 '      "x_dimension": 3,\n'
 '      "y_dimension": 30,\n'
 '      "z_dimension": 15\n'
 '     }\n'
 '    },\n'
 '    {\n'
 '     "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/750691876232b043dd3b6e2b0098bdbf",\n'
 '     "@type": "Sample",\n'
 '     "datasets": [],\n'
 '     "sections": [\n'
 '      {\n'
 '       "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/e80cd8fab25ec8e9cb41e3872e2129c7",\n'
 '       "@type": "Sample",\n'
 '       "datasets": [\n'
 '        {\n'
 '         "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/f6eb890063d13698feb11d39fa61e45a",\n'
 '         "@type": "Dataset",\n'
 '         "link": '
 '"https://portal.hubmapconsortium.org/browse/dataset/f6eb890063d13698feb11d39fa61e45a",\n'
 '         "technology": "RNAseq",\n'
 '         "cell_count": "6000",\n'
 '         "gene_count": "60286",\n'
 '         "organ_id": "http://purl.obolibrary.org/obo/UBERON_0002108",\n'
 '         "label": "Registered 11/3/2023, HuBMAP Process, TMC-Stanford",\n'
 '         "description": "Dataset Type: RNAseq [Salmon]",\n'
 '         "thumbnail": "assets/icons/ico-unknown.svg"\n'
 '        }\n'
 '       ],\n'
 '       "sample_type": "Tissue Section",\n'
 '       "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/e80cd8fab25ec8e9cb41e3872e2129c7",\n'
 '       "label": "Registered 2/16/2022, daniel Cotter, TMC-Stanford",\n'
 '       "description": "3 x 30 x 5 millimeter, 5 millimeter"\n'
 '      }\n'
 '     ],\n'
 '     "sample_type": "Tissue Block",\n'
 '     "link": '
 '"https://portal.hubmapconsortium.org/browse/sample/750691876232b043dd3b6e2b0098bdbf",\n'
 '     "label": "Registered 2/16/2022, amir Bahmani, TMC-Stanford",\n'
 '     "description": "3 x 30 x 15 millimeter, 5 millimeter, 3 Sections",\n'
 '     "rui_location": {\n'
 '      "@context": '
 '"https://hubmapconsortium.github.io/ccf-ontology/ccf-context.jsonld",\n'
 '      "@id": '
 '"http://purl.org/ccf/1.5/4ecffbfc-dc50-4140-95e8-4f97d5804f4f",\n'
 '      "@type": "SpatialEntity",\n'
 '      "ccf_annotations": [\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0002115",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14966",\n'
 '       "http://purl.obolibrary.org/obo/UBERON_0002114",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14926",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14928",\n'
 '       "http://purl.obolibrary.org/obo/FMA_15077",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14930",\n'
 '       "http://purl.obolibrary.org/obo/FMA_14929"\n'
 '      ],\n'
 '      "creation_date": "2022-02-16",\n'
 '      "creator": "Yiing Lin",\n'
 '      "creator_first_name": "Yiing",\n'
 '      "creator_last_name": "Lin",\n'
 '      "dimension_units": "millimeter",\n'
 '      "placement": {\n'
 '       "@context": '
 '"https://hubmapconsortium.github.io/hubmap-ontology/ccf-context.jsonld",\n'
 '       "@id": '
 '"http://purl.org/ccf/1.5/4ecffbfc-dc50-4140-95e8-4f97d5804f4f_placement",\n'
 '       "@type": "SpatialPlacement",\n'
 '       "placement_date": "2022-02-16",\n'
 '       "rotation_order": "XYZ",\n'
 '       "rotation_units": "degree",\n'
 '       "scaling_units": "ratio",\n'
 '       "target": "http://purl.org/ccf/latest/ccf.owl#VHFSmallIntestine",\n'
 '       "translation_units": "millimeter",\n'
 '       "x_rotation": 59,\n'
 '       "x_scaling": 1,\n'
 '       "x_translation": 81.38,\n'
 '       "y_rotation": 19,\n'
 '       "y_scaling": 1,\n'
 '       "y_translation": 156.91,\n'
 '       "z_rotation": -56,\n'
 '       "z_scaling": 1,\n'
 '       "z_translation": 21.022\n'
 '      },\n'
 '      "x_dimension": 3,\n'
 '      "y_dimension": 30,\n'
 '      "z_dimension": 15\n'
 '     }\n'
 '    },\n'
 '    {\n'
 '     "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/8cdf44a106338aada6da04c71eeb767e",\n'
 '     "@type": "Sample",\n'
 '     "datasets": [],\n'
 '     "sections": [\n'
 '      {\n'
 '       "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/96d320ccb24a968bc32571895cf1b05e",\n'
 '       "@type": "Sample",\n'
 '       "datasets": [\n'
 '        {\n'
 '         "@id": '
 '"https://entity.api.hubmapconsortium.org/entities/061b6c8f8e76f9be125f0f93e7734642",\n'